package com.tara.crm.production.repository;

import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

/**
 * 설비별 작업실적 (TPS, 회사 1000 / 공장 1000) — 더존 iCUBE "설비별 작업실적조회" 화면 쿼리를 옮긴 것. 조회 전용.
 *
 * <p>한 줄 = 작업실적(ME_WOCONF_DTL_X20329) 한 건 = 설비 × 작업일 × 계획(대수·앞/뒤). 계획(PP_PLANPRW_INFO)·주문/사전주문·
 * 용지·비가동(ME_EIOSTATE_HST)·투입인원을 붙이고 수율·가동률·OEE 를 계산한다. 컬럼이 90개가 넘어 DTO 대신
 * 컬럼명(camelCase) → 값 Map 으로 내려주고, 라벨·순서는 화면(`EquipmentPerfPage.tsx`)이 정한다.
 *
 * <p>정본과 다른 점: 기간(WRK_DT, 4곳)과 작업장 그룹(PP_WRKGRP_INFO.TOP_ORGN_CD, 4곳)을 바인딩으로 뺐다.
 * 그 외 조인·산식은 정본 그대로(사용자 제공 2026-10-02). 비가동(NOP_TEMP)은 정본처럼 기간 조건 없이 설비·실적번호로 잇는다.
 */
@Repository
@RequiredArgsConstructor
@ConditionalOnProperty(name = "oracle.enabled", havingValue = "true")
public class OracleEquipmentPerfRepository {

    @Qualifier("oracleJdbcTemplate")
    private final JdbcTemplate jdbcTemplate;

    private static final DateTimeFormatter BASIC = DateTimeFormatter.BASIC_ISO_DATE;

    /**
     * 설비 상세(표준선속 INSL_QT) — 정본은 `INNER JOIN PM_EQ_DTL … VLID_TO_DT='99991231'` 인데 제본 무선기 2대처럼
     * 유효기간 99991231 행이 없는 설비는 실적이 통째로 빠진다(2026-09 353행). 설비마다 가장 늦은 유효기간 행 하나를 LEFT 로 붙인다 —
     * 없으면 표준선속 0 → 성능가동률·표준시간만 0 이고 행은 남는다.
     */
    private static final String EQ_DTL_JOIN = """
            LEFT OUTER JOIN (
                SELECT COMPANY_CD, EQP_CD, INSL_QT
                FROM (SELECT COMPANY_CD, EQP_CD, INSL_QT,
                             ROW_NUMBER() OVER (PARTITION BY COMPANY_CD, EQP_CD ORDER BY VLID_TO_DT DESC) AS RN
                      FROM PM_EQ_DTL WHERE COMPANY_CD = '1000')
                WHERE RN = 1
            ) PED ON MWD.COMPANY_CD = PED.COMPANY_CD AND MWD.EQP_CD = PED.EQP_CD
            """;

    /** 공통 산식 — 시간당 생산량·선속·표준시간·가동률·OEE. 인쇄/제본 SELECT 끝에 같이 붙는다. */
    private static final String RATE_COLUMNS = """
            ,      CASE WHEN NVL(TIM.PRD_MINUTE, 0) = 0 THEN 0 ELSE ROUND(((MWD.WRK_QT / (TIM.PRD_MINUTE / 60))), 2) END AS TIME_PRD_QT
            ,      CASE WHEN NVL(TIM.PRD_MINUTE, 0) = 0 THEN 0 ELSE ROUND((MWD.WRK_QT / TIM.PRD_MINUTE), 2) END AS WRK_LS
            ,      CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.WRK_QT / (PED.INSL_QT) * 60), 2) END AS STD_PRD_MINUTE
            ,      CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.NET_QT / (PED.INSL_QT) * 60), 2) END AS STD_NET_MINUTE
            ,      PPI.WRK_UM, PPI.WRK_AMT
            ,      CITEM2.STD_LCLAS_CD, LCLAS.SYSDEF_NM AS STD_LCLAS_NM, CITEM2.STD_MLSFC_CD, MLSFC.SYSDEF_NM AS STD_MLSFC_NM
            ,      CITEM2.STD_S_CSF_CD, SCSF.SYSDEF_NM AS STD_S_CSF_NM
            ,      NVL(MEM.EMP_CNT, 0) AS EMP_CNT
            ,      CASE WHEN NVL(TIM.WRK_MINUTE, 0) = 0 THEN 0 ELSE ROUND(((NVL(TIM.PRD_MINUTE, 0) / TIM.WRK_MINUTE) * 100), 2) END AS TIME_RATE
            ,      CASE WHEN NVL(TIM.PRD_MINUTE, 0) = 0 THEN 0 ELSE ROUND((( CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.WRK_QT / (PED.INSL_QT) * 60), 2) END
                                                                            / TIM.PRD_MINUTE) * 100), 2) END AS PER_RATE
            ,      CASE WHEN (CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.WRK_QT / (PED.INSL_QT) * 60), 2) END) = 0 THEN 0
                        ELSE ROUND((((CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.NET_QT / (PED.INSL_QT) * 60), 2) END)
                                   / (CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.WRK_QT / (PED.INSL_QT) * 60), 2) END)) * 100), 2)
                   END AS GOOD_RATE
            ,      ROUND(((
                       CASE WHEN NVL(TIM.WRK_MINUTE, 0) = 0 THEN 0 ELSE ROUND(((NVL(TIM.PRD_MINUTE, 0) / TIM.WRK_MINUTE)), 2) END
                     * CASE WHEN NVL(TIM.PRD_MINUTE, 0) = 0 THEN 0 ELSE ROUND((( CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.WRK_QT / (PED.INSL_QT) * 60), 2) END
                                                                                / TIM.PRD_MINUTE)), 2) END
                     * CASE WHEN (CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.WRK_QT / (PED.INSL_QT) * 60), 2) END) = 0 THEN 0
                            ELSE ROUND((((CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.NET_QT / (PED.INSL_QT) * 60), 2) END)
                                       / (CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.WRK_QT / (PED.INSL_QT) * 60), 2) END))), 2)
                       END) * 100), 2) AS OEE
            """;

    /** 제품 분류·투입인원 조인 — 인쇄/제본 공통 꼬리. */
    private static String tailJoins(String memWhere) {
        return """
            INNER JOIN CI_ITEM CITEM2               ON PPI.ITEM_CD = CITEM2.ITEM_CD
            LEFT OUTER JOIN CI_CODEDTL LCLAS        ON CITEM2.STD_LCLAS_CD = LCLAS.SYSDEF_CD AND LCLAS.MODULE_CD = 'MA' AND LCLAS.FIELD_CD = 'P00260'
            LEFT OUTER JOIN CI_CODEDTL MLSFC        ON CITEM2.STD_MLSFC_CD = MLSFC.SYSDEF_CD AND MLSFC.MODULE_CD = 'MA' AND MLSFC.FIELD_CD = 'P00680'
            LEFT OUTER JOIN CI_CODEDTL SCSF         ON CITEM2.STD_S_CSF_CD = SCSF.SYSDEF_CD AND SCSF.MODULE_CD = 'MA' AND SCSF.FIELD_CD = 'P00390'
            LEFT OUTER JOIN (
                SELECT MEM.COMPANY_CD, MEM.PLANT_CD, MEM.WRK_CMPT_NO, MEM.WRK_CMPT_SQ, COUNT(EMP_NO) AS EMP_CNT
                FROM ME_WOCONFEM_INFO_X20329 MEM
                INNER JOIN PP_WRKGRP_INFO_X20329 PWI ON MEM.COMPANY_CD = PWI.COMPANY_CD AND MEM.PLANT_CD = PWI.PLANT_CD AND MEM.OP_CD = PWI.OP_CD
                WHERE MEM.COMPANY_CD = '1000' AND MEM.PLANT_CD = '1000'
                AND   %s
                GROUP BY MEM.COMPANY_CD, MEM.PLANT_CD, MEM.WRK_CMPT_NO, MEM.WRK_CMPT_SQ
            ) MEM ON MWD.COMPANY_CD = MEM.COMPANY_CD AND MWD.PLANT_CD = MEM.PLANT_CD AND MWD.WRK_CMPT_NO = MEM.WRK_CMPT_NO AND MWD.WRK_CMPT_SQ = MEM.WRK_CMPT_SQ
            """.formatted(memWhere);
    }

    /** 비가동 집계 — 정본처럼 기간 조건 없이 설비·실적번호(PAC_VR1/2)로 잇는다. */
    private static final String NOP_CTE = """
            NOP_TEMP AS (
                SELECT MEH.COMPANY_CD, MEH.EQP_CD, MEH.PAC_VR1, MEH.PAC_VR2,
                       SUM(CASE WHEN MNM.NONOP_TP_CD IN ('NOP', 'NCL') THEN MEH.DURATION_TM_QT ELSE 0 END) AS TOTAL_NOP_TIME,
                       SUM(CASE WHEN MNM.NONOP_TP_CD = 'NOP' THEN MEH.DURATION_TM_QT ELSE 0 END) AS NOP_TIME,
                       SUM(CASE WHEN MNM.NONOP_TP_CD = 'NCL' THEN MEH.DURATION_TM_QT ELSE 0 END) AS NCL_TIME
                FROM ME_EIOSTATE_HST MEH
                INNER JOIN ME_NONOP_MST MNM ON MEH.COMPANY_CD = MNM.COMPANY_CD AND MEH.NONOP_REASON_CD = MNM.NONOP_REASON_CD
                WHERE MEH.COMPANY_CD = '1000'
                GROUP BY MEH.COMPANY_CD, MEH.EQP_CD, MEH.PAC_VR1, MEH.PAC_VR2
            )
            """;

    /** 실적 일시 → 분 단위 구간. 인쇄/제본 공통(제본은 TOTAL_WRK_QT·투입량이 없어 그 부분만 인쇄 쿼리에 따로 있다). */
    private static final String TIME_MINUTES = """
            ROUND((TO_DATE(A.BASE_START_DTS, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(A.START_DTS, 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60, 2) AS START_MINUTE,
            ROUND((TO_DATE(A.WRK_START_DTS, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(A.BASE_START_DTS, 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60, 2) AS BASE_MINUTE,
            ROUND((TO_DATE(A.END_DTS, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(A.WRK_START_DTS, 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60, 2) AS GOOD_MINUTE,
            ROUND((TO_DATE(A.BASE_START_DTS, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(A.START_DTS, 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60, 2)
          + ROUND((TO_DATE(A.WRK_START_DTS, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(A.BASE_START_DTS, 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60, 2)
          + ROUND((TO_DATE(A.END_DTS, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(A.WRK_START_DTS, 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60, 2) AS WRK_MINUTE,
            ROUND((TO_DATE(A.WRK_START_DTS, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(A.BASE_START_DTS, 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60, 2)
          + ROUND((TO_DATE(A.END_DTS, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(A.WRK_START_DTS, 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60, 2) AS PRD_MINUTE
            """;

    /** 실적 일시 문자열(yyyy-MM-dd HH:mm:ss) — 시작/비품시작/양품시작/종료. */
    private static final String TIME_DTS = """
            CASE WHEN FN_COALESCE(MWD.PRWK_START_DT, 'N') = 'N' THEN NULL
                 ELSE TO_CHAR(TO_DATE(FN_CONCAT(MWD.PRWK_START_DT, FN_COALESCE(MWD.PRWK_START_TM, '000000')), 'YYYYMMDDHH24MISS'), 'YYYY-MM-DD HH24:MI:SS') END AS START_DTS,
            CASE WHEN MWD.BASE_START_DT IS NULL THEN NULL
                 ELSE TO_CHAR(TO_DATE(FN_CONCAT(MWD.BASE_START_DT, FN_COALESCE(MWD.BASE_START_TM, '000000')), 'YYYYMMDDHH24MISS'), 'YYYY-MM-DD HH24:MI:SS') END AS BASE_START_DTS,
            CASE WHEN MWD.WRK_START_DT IS NULL THEN NULL
                 ELSE TO_CHAR(TO_DATE(FN_CONCAT(MWD.WRK_START_DT, FN_COALESCE(MWD.WRK_START_TM, '000000')), 'YYYYMMDDHH24MISS'), 'YYYY-MM-DD HH24:MI:SS') END AS WRK_START_DTS,
            CASE WHEN FN_COALESCE(MWD.PRWK_END_DT, 'N') = 'N' THEN NULL
                 ELSE TO_CHAR(TO_DATE(FN_CONCAT(MWD.PRWK_END_DT, FN_COALESCE(MWD.PRWK_END_TM, '000000')), 'YYYYMMDDHH24MISS'), 'YYYY-MM-DD HH24:MI:SS') END AS END_DTS
            """;

    /**
     * 제본 (WC40, 접지 OP406 제외 — 무선·중철·풀입/재단만, 사용자 결정 2026-10-02). ERP "설비별 작업실적조회(제본)" 쿼리 이식.
     * 정본과 다른 점: 바인딩 밀림 수정(PES.LANG_CD='KO', PLANT_CD='1000', 기간), 설비 상세는 EQ_DTL_JOIN(LEFT·최신 행).
     * 폐기수량(DIS_QT = 접지 여분실적 합(전 기간) − 제본 여분 합(조회 기간))은 정본 산식 그대로 — 대부분 음수로 나오며 정의 확인 대기.
     */
    private static final String BIND_SQL = """
            WITH ORDER_TEMP AS (
                SELECT SOM.COMPANY_CD, SOM.PLAN_PLANT_CD AS PLANT_CD, SOM.ORDDOC_NO, SOD.ORDDOC_SQ, SOM.DEPT_CD, MDM.DEPT_NM, SOM.PARTNER_CD, CPM.PARTNER_NM,
                       SOD.ITEM_CD, SOD.SPCFCS_ITEM_NM, SOM.WRK_FG, MC.SYSDEF_NM AS WRK_FG_NM,
                       CONCAT(CONCAT(TO_CHAR(SOD.HRZN_QT), '*'), TO_CHAR(SOD.VTCL_QT)) AS SPEC_QT, SOD.PACK_MTHD_CD, MC2.SYSDEF_NM AS PACK_MTHD_NM, SOD.PACK_UNIT_DC
                FROM SD_ORDER_MST_X20329 SOM
                INNER JOIN SD_ORDER_DTL_X20329 SOD ON SOM.COMPANY_CD = SOD.COMPANY_CD AND SOM.ORDDOC_NO = SOD.ORDDOC_NO
                LEFT OUTER JOIN MA_DEPT_MST MDM    ON SOM.COMPANY_CD = MDM.COMPANY_CD AND SOM.DEPT_CD = MDM.DEPT_CD
                LEFT OUTER JOIN CI_PARTNER_MST CPM ON SOM.PARTNER_CD = CPM.PARTNER_CD
                LEFT OUTER JOIN MA_CODEDTL MC      ON SOM.COMPANY_CD = MC.COMPANY_CD AND SOM.WRK_FG = MC.SYSDEF_CD AND MC.MODULE_CD = 'SD' AND MC.FIELD_CD = 'Z024_20329'
                LEFT OUTER JOIN MA_CODEDTL MC2     ON SOD.COMPANY_CD = MC2.COMPANY_CD AND SOD.PACK_MTHD_CD = MC2.SYSDEF_CD AND MC2.MODULE_CD = 'SD' AND MC2.FIELD_CD = 'Z006_20329'
                WHERE SOM.COMPANY_CD = '1000' AND SOM.PLAN_PLANT_CD = '1000'
                UNION ALL
                SELECT SOM.COMPANY_CD, SOM.PLANT_CD, SOM.PLAN_ORD_NO, SOD.PLAN_ORD_SQ, SOM.DEPT_CD, MDM.DEPT_NM, SOM.PARTNER_CD, CPM.PARTNER_NM,
                       SOD.ITEM_CD, SOD.SPCFCS_ITEM_NM, SOM.WRK_FG, MC.SYSDEF_NM,
                       CONCAT(CONCAT(TO_CHAR(SOD.HRZN_QT), '*'), TO_CHAR(SOD.VTCL_QT)), SOD.PACK_MTHD_CD, MC2.SYSDEF_NM, SOD.PACK_UNIT_DC
                FROM PP_PREORD_MST_X20329 SOM
                INNER JOIN PP_PREORD_DTL_X20329 SOD ON SOM.COMPANY_CD = SOD.COMPANY_CD AND SOM.PLAN_ORD_NO = SOD.PLAN_ORD_NO
                LEFT OUTER JOIN MA_DEPT_MST MDM     ON SOM.COMPANY_CD = MDM.COMPANY_CD AND SOM.DEPT_CD = MDM.DEPT_CD
                LEFT OUTER JOIN CI_PARTNER_MST CPM  ON SOM.PARTNER_CD = CPM.PARTNER_CD
                LEFT OUTER JOIN MA_CODEDTL MC       ON SOM.COMPANY_CD = MC.COMPANY_CD AND SOM.WRK_FG = MC.SYSDEF_CD AND MC.MODULE_CD = 'SD' AND MC.FIELD_CD = 'Z024_20329'
                LEFT OUTER JOIN MA_CODEDTL MC2      ON SOD.COMPANY_CD = MC2.COMPANY_CD AND SOD.PACK_MTHD_CD = MC2.SYSDEF_CD AND MC2.MODULE_CD = 'SD' AND MC2.FIELD_CD = 'Z006_20329'
                WHERE SOM.COMPANY_CD = '1000' AND SOM.PLANT_CD = '1000'
            ), BEF_PRD_TEMP AS (
                -- 접지(OP406) 실적 — 전공정 여분 합(기간 조건 없음, 정본대로)
                SELECT MWD.COMPANY_CD, MWD.PLANT_CD, MWD.PLAN_NO, MWD.PLAN_SQ,
                       SUM(NVL(MWD.WRK_QT, 0)) AS BEF_WRK_QT, SUM(NVL(MWD.NET_QT, 0)) AS BEF_NET_QT, SUM(NVL(MWD.SPRE_QT, 0)) AS BEF_SPRE_QT, SUM(NVL(MWD.BAD_QT, 0)) AS BEF_BAD_QT
                FROM ME_WOCONF_DTL_X20329 MWD
                INNER JOIN PP_PLANBBND_INFO_X20329 PPI ON MWD.COMPANY_CD = PPI.COMPANY_CD AND MWD.PLANT_CD = PPI.PLANT_CD AND MWD.PLAN_NO = PPI.PLAN_NO
                                                      AND MWD.PLAN_HIS_SQ = PPI.PLAN_HIS_SQ AND MWD.PLAN_SQ = PPI.PLAN_SQ AND MWD.PLAN_LOW_SQ = PPI.PLAN_LOW_SQ
                INNER JOIN PP_WRKGRP_INFO_X20329 PWI   ON MWD.COMPANY_CD = PWI.COMPANY_CD AND MWD.PLANT_CD = PWI.PLANT_CD AND MWD.EQP_CD = PWI.EQP_CD
                WHERE MWD.COMPANY_CD = '1000' AND MWD.PLANT_CD = '1000' AND PWI.TOP_ORGN_CD = 'WC40' AND PWI.UP_ORGN_CD = 'OP406'
                GROUP BY MWD.COMPANY_CD, MWD.PLANT_CD, MWD.PLAN_NO, MWD.PLAN_SQ
            ), TIME_TEMP AS (
                SELECT A.COMPANY_CD, A.PLANT_CD, A.WRK_CMPT_NO, A.WRK_CMPT_SQ, A.START_DTS, A.BASE_START_DTS, A.WRK_START_DTS, A.END_DTS,
            """ + TIME_MINUTES + """
                FROM (
                    SELECT MWD.COMPANY_CD, MWD.PLANT_CD, MWD.WRK_CMPT_NO, MWD.WRK_CMPT_SQ,
            """ + TIME_DTS + """
                    FROM ME_WOCONF_DTL_X20329 MWD
                    INNER JOIN PP_WRKGRP_INFO_X20329 PWI ON MWD.COMPANY_CD = PWI.COMPANY_CD AND MWD.PLANT_CD = PWI.PLANT_CD AND MWD.EQP_CD = PWI.EQP_CD
                    WHERE MWD.COMPANY_CD = '1000' AND MWD.PLANT_CD = '1000'
                    AND   MWD.WRK_DT BETWEEN ? AND ?
                    AND   PWI.TOP_ORGN_CD = 'WC40' AND PWI.UP_ORGN_CD <> 'OP406'
                ) A
            ), """ + NOP_CTE + """
            SELECT MWD.COMPANY_CD, MWD.PLANT_CD, MPM.PLANT_NM, MWD.EQP_CD, PES.EQP_NM, MWD.WRK_DT,
                   PWI.UP_ORGN_CD AS OP_CD, MCOP.SYSDEF_NM AS OP_NM,
                   TIM.START_DTS, TIM.BASE_START_DTS, TIM.WRK_START_DTS, TIM.END_DTS,
                   MWD.SHIFT_CD, MC.SYSDEF_NM AS SHIFT_NM, NVL(MEI.BWRK_TM, 0) AS BWRK_TM,
                   MWD.ORDDOC_NO, MWD.PLAN_NO, MWD.PLAN_HIS_SQ, MWD.PLAN_SQ, MWD.PLAN_LOW_SQ,
                   ORD.ITEM_CD, ORD.WRK_FG, ORD.WRK_FG_NM, ORD.DEPT_CD, ORD.DEPT_NM,
                   MITEM.PRDUCTGRP_CD, MC2.SYSDEF_NM AS PRDUCTGRP_NM, ORD.PARTNER_CD, ORD.PARTNER_NM, ORD.SPCFCS_ITEM_NM,
                   MWD.PAC_VR3, ORD.SPEC_QT, PPI.TOT_PGS, PPI.FULL_PRPCNT_QT, ORD.PACK_UNIT_DC, ORD.PACK_MTHD_CD, ORD.PACK_MTHD_NM,
                   NVL(BPT.BEF_SPRE_QT, 0) AS BEF_SPRE_QT,
                   NVL((BPT.BEF_SPRE_QT - SUM(MWD.SPRE_QT) OVER (PARTITION BY MWD.COMPANY_CD, MWD.PLANT_CD, MWD.PLAN_NO, MWD.PLAN_SQ)), 0) AS DIS_QT,
                   PPI.ORD_QT, MWD.SPRE_QT + MWD.BAD_QT AS INPUT_QT,
                   MWD.WRK_QT, MWD.NET_QT, MWD.SPRE_QT, MWD.BAD_QT,
                   CASE WHEN MWD.WRK_QT = 0 THEN 0 ELSE ROUND(((MWD.NET_QT + MWD.SPRE_QT) / MWD.WRK_QT) * 100, 2) END AS BBND_YIELD,
                   CASE WHEN MWD.NET_QT + MWD.SPRE_QT = 0 THEN 0 ELSE ROUND((MWD.NET_QT / (MWD.NET_QT + MWD.SPRE_QT)) * 100, 2) END AS SPRE_RATE,
                   NVL(TIM.START_MINUTE, 0) AS START_MINUTE, NVL(TIM.BASE_MINUTE, 0) AS BASE_MINUTE, NVL(TIM.GOOD_MINUTE, 0) AS GOOD_MINUTE,
                   NVL(TIM.WRK_MINUTE, 0) AS WRK_MINUTE, NVL(TIM.PRD_MINUTE, 0) AS PRD_MINUTE,
                   NVL(NOP.TOTAL_NOP_TIME, 0) AS TOTAL_NOP_TIME, NVL(NOP.NOP_TIME, 0) AS NOP_TIME, NVL(NOP.NCL_TIME, 0) AS NCL_TIME,
                   NVL(TIM.PRD_MINUTE, 0) + NVL(NOP.TOTAL_NOP_TIME, 0) AS RUN_TIME,
                   PPI.ORD_UNIT_CD AS UNIT_CD, NVL(PED.INSL_QT, 0) AS INSL_QT, NVL(MWD.PAC_VR2, 0) AS PAC_VR2
            """ + RATE_COLUMNS + """
            FROM ME_WOCONF_DTL_X20329 MWD
            INNER JOIN MA_PLANT_MST MPM             ON MWD.COMPANY_CD = MPM.COMPANY_CD AND MWD.PLANT_CD = MPM.PLANT_CD
            """ + EQ_DTL_JOIN + """
            INNER JOIN PM_EQ_SDTL PES               ON MWD.COMPANY_CD = PES.COMPANY_CD AND MWD.EQP_CD = PES.EQP_CD AND PES.LANG_CD = 'KO'
            INNER JOIN PP_WRKGRP_INFO_X20329 PWI    ON MWD.COMPANY_CD = PWI.COMPANY_CD AND MWD.PLANT_CD = PWI.PLANT_CD AND MWD.EQP_CD = PWI.EQP_CD
            LEFT OUTER JOIN MA_CODEDTL MCOP         ON MCOP.COMPANY_CD = MWD.COMPANY_CD AND MCOP.MODULE_CD = 'PP' AND MCOP.FIELD_CD = 'Z005_20329' AND MCOP.SYSDEF_CD = PWI.UP_ORGN_CD
            LEFT OUTER JOIN MA_CODEDTL MC           ON MWD.COMPANY_CD = MC.COMPANY_CD AND MWD.SHIFT_CD = MC.SYSDEF_CD AND MC.MODULE_CD = 'ME' AND MC.FIELD_CD = 'P00520'
            INNER JOIN PP_PLANBBND_INFO_X20329 PPI  ON MWD.COMPANY_CD = PPI.COMPANY_CD AND MWD.PLANT_CD = PPI.PLANT_CD AND MWD.PLAN_NO = PPI.PLAN_NO
                                                   AND MWD.PLAN_HIS_SQ = PPI.PLAN_HIS_SQ AND MWD.PLAN_SQ = PPI.PLAN_SQ AND MWD.PLAN_LOW_SQ = PPI.PLAN_LOW_SQ
            INNER JOIN MA_ITEM MITEM                ON PPI.COMPANY_CD = MITEM.COMPANY_CD AND PPI.ITEM_CD = MITEM.ITEM_CD
            INNER JOIN ORDER_TEMP ORD               ON PPI.COMPANY_CD = ORD.COMPANY_CD AND PPI.PLANT_CD = ORD.PLANT_CD AND PPI.ORDDOC_NO = ORD.ORDDOC_NO AND PPI.ORDDOC_SQ = ORD.ORDDOC_SQ
            LEFT OUTER JOIN MA_CODEDTL MC2          ON MITEM.COMPANY_CD = MC2.COMPANY_CD AND MITEM.PRDUCTGRP_CD = MC2.SYSDEF_CD AND MC2.MODULE_CD = 'MA' AND MC2.FIELD_CD = 'S00020'
            LEFT OUTER JOIN ME_EQPDNBWRK_INFO_X20329 MEI ON MWD.COMPANY_CD = MEI.COMPANY_CD AND MWD.PLANT_CD = MEI.PLANT_CD AND MWD.EQP_CD = MEI.EQP_CD
                                                   AND MWD.SHIFT_CD = MEI.DN_FG AND MWD.WRK_DT = MEI.WRK_DT
            LEFT OUTER JOIN BEF_PRD_TEMP BPT        ON MWD.COMPANY_CD = BPT.COMPANY_CD AND MWD.PLANT_CD = BPT.PLANT_CD AND MWD.PLAN_NO = BPT.PLAN_NO AND MWD.PLAN_SQ = BPT.PLAN_SQ
            INNER JOIN TIME_TEMP TIM                ON MWD.COMPANY_CD = TIM.COMPANY_CD AND MWD.PLANT_CD = TIM.PLANT_CD AND MWD.WRK_CMPT_NO = TIM.WRK_CMPT_NO AND MWD.WRK_CMPT_SQ = TIM.WRK_CMPT_SQ
            LEFT OUTER JOIN NOP_TEMP NOP            ON MWD.COMPANY_CD = NOP.COMPANY_CD AND MWD.EQP_CD = NOP.EQP_CD AND MWD.WRK_CMPT_NO = NOP.PAC_VR1 AND MWD.WRK_CMPT_SQ = NOP.PAC_VR2
            """ + tailJoins("PWI.TOP_ORGN_CD = 'WC40' AND PWI.UP_ORGN_CD <> 'OP406'") + """
            WHERE MWD.COMPANY_CD = '1000' AND MWD.PLANT_CD = '1000'
            AND   MWD.WRK_DT BETWEEN ? AND ?
            AND   PWI.TOP_ORGN_CD = 'WC40' AND PWI.UP_ORGN_CD <> 'OP406'
            ORDER BY MWD.EQP_CD, MWD.PLAN_NO, MWD.PLAN_HIS_SQ, MWD.PLAN_SQ, MWD.PLAN_LOW_SQ, MWD.WRK_DT
            """;

    private static final String SQL = """
            WITH ORDER_TEMP AS (
                -- 주문목록 -> 주문,의뢰 적용
                SELECT SOM.COMPANY_CD, SOM.PLAN_PLANT_CD AS PLANT_CD, SOM.ORDDOC_NO, SOD.ORDDOC_SQ,
                       SOM.DEPT_CD, MDM.DEPT_NM, SOM.PARTNER_CD, CPM.PARTNER_NM, SOD.ITEM_CD, SOD.SPCFCS_ITEM_NM,
                       SOM.WRK_FG, MC.SYSDEF_NM AS WRK_FG_NM
                FROM SD_ORDER_MST_X20329 SOM
                INNER JOIN SD_ORDER_DTL_X20329 SOD ON SOM.COMPANY_CD = SOD.COMPANY_CD AND SOM.ORDDOC_NO = SOD.ORDDOC_NO
                LEFT OUTER JOIN MA_DEPT_MST MDM    ON SOM.COMPANY_CD = MDM.COMPANY_CD AND SOM.DEPT_CD = MDM.DEPT_CD
                LEFT OUTER JOIN CI_PARTNER_MST CPM ON SOM.PARTNER_CD = CPM.PARTNER_CD
                LEFT OUTER JOIN MA_CODEDTL MC      ON SOM.COMPANY_CD = MC.COMPANY_CD AND SOM.WRK_FG = MC.SYSDEF_CD
                                                  AND MC.MODULE_CD = 'SD' AND MC.FIELD_CD = 'Z024_20329'
                WHERE SOM.COMPANY_CD = '1000' AND SOM.PLAN_PLANT_CD = '1000'
                UNION ALL
                SELECT SOM.COMPANY_CD, SOM.PLANT_CD, SOM.PLAN_ORD_NO AS ORDDOC_NO, SOD.PLAN_ORD_SQ AS ORDDOC_SQ,
                       SOM.DEPT_CD, MDM.DEPT_NM, SOM.PARTNER_CD, CPM.PARTNER_NM, SOD.ITEM_CD, SOD.SPCFCS_ITEM_NM,
                       SOM.WRK_FG, MC.SYSDEF_NM AS WRK_FG_NM
                FROM PP_PREORD_MST_X20329 SOM
                INNER JOIN PP_PREORD_DTL_X20329 SOD ON SOM.COMPANY_CD = SOD.COMPANY_CD AND SOM.PLAN_ORD_NO = SOD.PLAN_ORD_NO
                LEFT OUTER JOIN MA_DEPT_MST MDM     ON SOM.COMPANY_CD = MDM.COMPANY_CD AND SOM.DEPT_CD = MDM.DEPT_CD
                LEFT OUTER JOIN CI_PARTNER_MST CPM  ON SOM.PARTNER_CD = CPM.PARTNER_CD
                LEFT OUTER JOIN MA_CODEDTL MC       ON SOM.COMPANY_CD = MC.COMPANY_CD AND SOM.WRK_FG = MC.SYSDEF_CD
                                                   AND MC.MODULE_CD = 'SD' AND MC.FIELD_CD = 'Z024_20329'
                WHERE SOM.COMPANY_CD = '1000' AND SOM.PLANT_CD = '1000'
            ), FIRST_AB_TEMP AS (
                -- 앞/뒤중 먼저 등록한 실적 내역 확인
                SELECT MWD.COMPANY_CD, MWD.PLANT_CD, MWD.ORDDOC_NO, MWD.EQP_CD, MWD.PLAN_NO, MWD.PLAN_HIS_SQ, MWD.PLAN_SQ, MWD.PLAN_LOW_SQ,
                       MAX(MWD.PAC_VR1) KEEP (DENSE_RANK FIRST ORDER BY MWD.PRWK_START_DT, MWD.PRWK_START_TM) AS FIRST_AB
                FROM ME_WOCONF_DTL_X20329 MWD
                INNER JOIN PP_WRKGRP_INFO_X20329 PWI ON MWD.COMPANY_CD = PWI.COMPANY_CD AND MWD.PLANT_CD = PWI.PLANT_CD AND MWD.EQP_CD = PWI.EQP_CD
                WHERE MWD.COMPANY_CD = '1000' AND MWD.PLANT_CD = '1000'
                AND   PWI.TOP_ORGN_CD = ?
                AND   MWD.WRK_DT BETWEEN ? AND ?
                GROUP BY MWD.COMPANY_CD, MWD.PLANT_CD, MWD.ORDDOC_NO, MWD.EQP_CD, MWD.PLAN_NO, MWD.PLAN_HIS_SQ, MWD.PLAN_SQ, MWD.PLAN_LOW_SQ
            ), TOTAL_INPUT_AGG AS (
                -- 먼저 실적잡은 면의 정미 여분 합
                SELECT MWD.COMPANY_CD, MWD.PLANT_CD, MWD.ORDDOC_NO, MWD.EQP_CD, MWD.PLAN_NO, MWD.PLAN_HIS_SQ, MWD.PLAN_SQ, MWD.PLAN_LOW_SQ, MWD.PAC_VR1,
                       SUM(NVL(MWD.NET_QT, 0) + NVL(MWD.SPRE_QT, 0)) AS TOTAL_INPUT_QT
                FROM ME_WOCONF_DTL_X20329 MWD
                WHERE MWD.COMPANY_CD = '1000' AND MWD.PLANT_CD = '1000'
                AND   MWD.PAC_VR1 IS NOT NULL
                AND   MWD.WRK_DT BETWEEN ? AND ?
                GROUP BY MWD.COMPANY_CD, MWD.PLANT_CD, MWD.ORDDOC_NO, MWD.EQP_CD, MWD.PLAN_NO, MWD.PLAN_HIS_SQ, MWD.PLAN_SQ, MWD.PLAN_LOW_SQ, MWD.PAC_VR1
            ), TIME_PRD_TEMP AS (
                -- 실적 및 일시
                SELECT A.COMPANY_CD, A.PLANT_CD, A.WRK_CMPT_NO, A.WRK_CMPT_SQ, A.START_DTS, A.BASE_START_DTS, A.WRK_START_DTS, A.END_DTS, A.TOTAL_WRK_QT,
                       ROUND((TO_DATE(A.BASE_START_DTS, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(A.START_DTS, 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60, 2) AS START_MINUTE,
                       ROUND((TO_DATE(A.WRK_START_DTS, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(A.BASE_START_DTS, 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60, 2) AS BASE_MINUTE,
                       ROUND((TO_DATE(A.END_DTS, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(A.WRK_START_DTS, 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60, 2) AS GOOD_MINUTE,
                       ROUND((TO_DATE(A.BASE_START_DTS, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(A.START_DTS, 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60, 2)
                     + ROUND((TO_DATE(A.WRK_START_DTS, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(A.BASE_START_DTS, 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60, 2)
                     + ROUND((TO_DATE(A.END_DTS, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(A.WRK_START_DTS, 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60, 2) AS WRK_MINUTE,
                       ROUND((TO_DATE(A.WRK_START_DTS, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(A.BASE_START_DTS, 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60, 2)
                     + ROUND((TO_DATE(A.END_DTS, 'YYYY-MM-DD HH24:MI:SS') - TO_DATE(A.WRK_START_DTS, 'YYYY-MM-DD HH24:MI:SS')) * 24 * 60, 2) AS PRD_MINUTE,
                       A.PLAN_NET_QT, A.PLAN_SPRE_QT, A.TOTAL_INPUT_QT, A.ITEM_TYPE_NM
                FROM (
                    SELECT MWD.COMPANY_CD, MWD.PLANT_CD, MWD.WRK_CMPT_NO, MWD.WRK_CMPT_SQ,
                           SUM(MWD.WRK_QT) OVER (PARTITION BY MWD.COMPANY_CD, MWD.PLANT_CD, MWD.PLAN_NO, MWD.PLAN_HIS_SQ, MWD.PLAN_SQ, MWD.PLAN_LOW_SQ, MWD.PAC_VR1) AS TOTAL_WRK_QT,
                           CASE WHEN FN_COALESCE(MWD.PRWK_START_DT, 'N') = 'N' THEN NULL
                                ELSE TO_CHAR(TO_DATE(FN_CONCAT(MWD.PRWK_START_DT, FN_COALESCE(MWD.PRWK_START_TM, '000000')), 'YYYYMMDDHH24MISS'), 'YYYY-MM-DD HH24:MI:SS') END AS START_DTS,
                           CASE WHEN MWD.BASE_START_DT IS NULL THEN NULL
                                ELSE TO_CHAR(TO_DATE(FN_CONCAT(MWD.BASE_START_DT, FN_COALESCE(MWD.BASE_START_TM, '000000')), 'YYYYMMDDHH24MISS'), 'YYYY-MM-DD HH24:MI:SS') END AS BASE_START_DTS,
                           CASE WHEN MWD.WRK_START_DT IS NULL THEN NULL
                                ELSE TO_CHAR(TO_DATE(FN_CONCAT(MWD.WRK_START_DT, FN_COALESCE(MWD.WRK_START_TM, '000000')), 'YYYYMMDDHH24MISS'), 'YYYY-MM-DD HH24:MI:SS') END AS WRK_START_DTS,
                           CASE WHEN FN_COALESCE(MWD.PRWK_END_DT, 'N') = 'N' THEN NULL
                                ELSE TO_CHAR(TO_DATE(FN_CONCAT(MWD.PRWK_END_DT, FN_COALESCE(MWD.PRWK_END_TM, '000000')), 'YYYYMMDDHH24MISS'), 'YYYY-MM-DD HH24:MI:SS') END AS END_DTS,
                           CASE WHEN PPI.GRPG_YN = 'Y' THEN FN_COALESCE(PPI.VNR_NET_QT, 0) * 500 * CASE WHEN (PPI.DIVD_CNT IS NULL OR PPI.DIVD_CNT = 0) THEN 1 ELSE PPI.DIVD_CNT END
                                ELSE FN_COALESCE(PPI.NET_QT, 0) * 500 * CASE WHEN (PPI.DIVD_CNT IS NULL OR PPI.DIVD_CNT = 0) THEN 1 ELSE PPI.DIVD_CNT END END AS PLAN_NET_QT,
                           CASE WHEN PPI.GRPG_YN = 'Y' THEN FN_COALESCE(PPI.VNR_ADJT_QT, 0) * 500 * CASE WHEN (PPI.DIVD_CNT IS NULL OR PPI.DIVD_CNT = 0) THEN 1 ELSE PPI.DIVD_CNT END
                                ELSE FN_COALESCE(PPI.ADJT_QT, 0) * 500 * CASE WHEN (PPI.DIVD_CNT IS NULL OR PPI.DIVD_CNT = 0) THEN 1 ELSE PPI.DIVD_CNT END END AS PLAN_SPRE_QT,
                           CASE WHEN MWD.PAC_VR1 = FP.FIRST_AB THEN
                                    CASE WHEN PPI.GRPG_YN = 'Y' THEN NVL(PPI.VNR_NET_QT, 0) * 500 * NVL(NULLIF(PPI.DIVD_CNT, 0), 1)
                                         ELSE NVL(PPI.NET_QT, 0) * 500 * NVL(NULLIF(PPI.DIVD_CNT, 0), 1) END
                                  + CASE WHEN PPI.GRPG_YN = 'Y' THEN NVL(PPI.VNR_ADJT_QT, 0) * 500 * NVL(NULLIF(PPI.DIVD_CNT, 0), 1)
                                         ELSE NVL(PPI.ADJT_QT, 0) * 500 * NVL(NULLIF(PPI.DIVD_CNT, 0), 1) END
                                ELSE NVL(TIA.TOTAL_INPUT_QT, 0) END AS TOTAL_INPUT_QT,
                           CASE WHEN MWD.PAC_VR1 = FP.FIRST_AB THEN '반제품' ELSE '완제품' END AS ITEM_TYPE_NM
                    FROM ME_WOCONF_DTL_X20329 MWD
                    INNER JOIN PP_WRKGRP_INFO_X20329 PWI  ON MWD.COMPANY_CD = PWI.COMPANY_CD AND MWD.PLANT_CD = PWI.PLANT_CD AND MWD.EQP_CD = PWI.EQP_CD
                    INNER JOIN PP_PLANPRW_INFO_X20329 PPI ON MWD.COMPANY_CD = PPI.COMPANY_CD AND MWD.PLANT_CD = PPI.PLANT_CD AND MWD.PLAN_NO = PPI.PLAN_NO
                                                         AND MWD.PLAN_HIS_SQ = PPI.PLAN_HIS_SQ AND MWD.PLAN_SQ = PPI.PLAN_SQ AND MWD.PLAN_LOW_SQ = PPI.PLAN_LOW_SQ
                    LEFT OUTER JOIN FIRST_AB_TEMP FP      ON MWD.COMPANY_CD = FP.COMPANY_CD AND MWD.PLANT_CD = FP.PLANT_CD AND MWD.ORDDOC_NO = FP.ORDDOC_NO AND MWD.EQP_CD = FP.EQP_CD
                                                         AND MWD.PLAN_NO = FP.PLAN_NO AND MWD.PLAN_HIS_SQ = FP.PLAN_HIS_SQ AND MWD.PLAN_SQ = FP.PLAN_SQ AND MWD.PLAN_LOW_SQ = FP.PLAN_LOW_SQ
                    LEFT OUTER JOIN TOTAL_INPUT_AGG TIA   ON MWD.COMPANY_CD = TIA.COMPANY_CD AND MWD.PLANT_CD = TIA.PLANT_CD AND MWD.ORDDOC_NO = TIA.ORDDOC_NO AND MWD.EQP_CD = TIA.EQP_CD
                                                         AND MWD.PLAN_NO = TIA.PLAN_NO AND MWD.PLAN_HIS_SQ = TIA.PLAN_HIS_SQ AND MWD.PLAN_SQ = TIA.PLAN_SQ AND MWD.PLAN_LOW_SQ = TIA.PLAN_LOW_SQ
                                                         AND MWD.PAC_VR1 = TIA.PAC_VR1
                    WHERE MWD.COMPANY_CD = '1000' AND MWD.PLANT_CD = '1000'
                    AND   PWI.TOP_ORGN_CD = ?
                    AND   MWD.WRK_DT BETWEEN ? AND ?
                ) A
            ), NOP_TEMP AS (
                -- 비가동정보
                SELECT MEH.COMPANY_CD, MEH.EQP_CD, MEH.PAC_VR1, MEH.PAC_VR2,
                       SUM(CASE WHEN MNM.NONOP_TP_CD IN ('NOP', 'NCL') THEN MEH.DURATION_TM_QT ELSE 0 END) AS TOTAL_NOP_TIME,
                       SUM(CASE WHEN MNM.NONOP_TP_CD = 'NOP' THEN MEH.DURATION_TM_QT ELSE 0 END) AS NOP_TIME,
                       SUM(CASE WHEN MNM.NONOP_TP_CD = 'NCL' THEN MEH.DURATION_TM_QT ELSE 0 END) AS NCL_TIME
                FROM ME_EIOSTATE_HST MEH
                INNER JOIN ME_NONOP_MST MNM ON MEH.COMPANY_CD = MNM.COMPANY_CD AND MEH.NONOP_REASON_CD = MNM.NONOP_REASON_CD
                WHERE MEH.COMPANY_CD = '1000'
                GROUP BY MEH.COMPANY_CD, MEH.EQP_CD, MEH.PAC_VR1, MEH.PAC_VR2
            )
            SELECT MWD.COMPANY_CD, MWD.PLANT_CD, MPM.PLANT_NM, MWD.EQP_CD, PES.EQP_NM, MWD.WRK_DT,
                   PWI.UP_ORGN_CD AS OP_CD, MCOP.SYSDEF_NM AS OP_NM,
                   TIM.START_DTS, TIM.BASE_START_DTS, TIM.WRK_START_DTS, TIM.END_DTS,
                   MWD.SHIFT_CD, MC.SYSDEF_NM AS SHIFT_NM, NVL(MEI.BWRK_TM, 0) AS BWRK_TM,
                   MWD.ORDDOC_NO, MWD.PLAN_NO, MWD.PLAN_HIS_SQ, MWD.PLAN_SQ, MWD.PLAN_LOW_SQ,
                   ORD.ITEM_CD, ORD.WRK_FG, ORD.WRK_FG_NM, ORD.DEPT_CD, ORD.DEPT_NM,
                   MITEM.PRDUCTGRP_CD, MC2.SYSDEF_NM AS PRDUCTGRP_NM, ORD.PARTNER_CD, ORD.PARTNER_NM, ORD.SPCFCS_ITEM_NM,
                   PPI.CONFIG_CD, MC3.SYSDEF_NM AS CONFIG_NM, PPI.PRPCNT_SQ, MWD.PAC_VR1,
                   CONCAT(CONCAT(TO_CHAR(PPI.GNRL_PRW_BEF_QT), '*'), PPI.GNRL_PRW_AFTR_QT) AS GNRL_PRW_QT,
                   CONCAT(CONCAT(TO_CHAR(PPI.SPCLR_PRW_BEF_QT), '*'), PPI.SPCLR_PRW_AFTR_QT) AS SPCLR_PRW_QT,
                   MWD.PAC_VR3, NVL(PPI.GRPG_YN, 'N') AS GRPG_YN,
                   NVL(TIM.PLAN_NET_QT, 0) AS PLAN_NET_QT, NVL(TIM.PLAN_SPRE_QT, 0) AS PLAN_SPRE_QT,
                   CASE WHEN NVL(TIM.PLAN_NET_QT, 0) = 0 THEN 0 ELSE ROUND(((TIM.PLAN_SPRE_QT / TIM.PLAN_NET_QT) * 100), 2) END AS SPRE_RATE,
                   NVL(TIM.PLAN_NET_QT, 0) + NVL(TIM.PLAN_SPRE_QT, 0) AS PLAN_QT,
                   NVL(TIM.TOTAL_WRK_QT, 0) AS TOTAL_WRK_QT, NVL(TIM.TOTAL_INPUT_QT, 0) AS TOTAL_INPUT_QT,
                   NVL(MWD.WRK_QT, 0) AS WRK_QT, NVL(MWD.NET_QT, 0) AS NET_QT, NVL(MWD.SPRE_QT, 0) AS SPRE_QT, NVL(MWD.BAD_QT, 0) AS BAD_QT,
                   NVL(MWD.WRK_QT, 0) - NVL(TIM.TOTAL_INPUT_QT, 0) AS IR_QT,
                   CASE WHEN NVL(MWD.NET_QT, 0) = 0 THEN 0 ELSE ROUND(((MWD.SPRE_QT / MWD.NET_QT) * 100), 2) END AS PRD_SPRE_RATE,
                   CASE WHEN NVL(MWD.WRK_QT, 0) = 0 THEN 0 ELSE ROUND((((MWD.SPRE_QT + MWD.NET_QT) / MWD.WRK_QT) * 100), 2) END AS PRW_YIELD,
                   CASE WHEN TIM.TOTAL_INPUT_QT = 0 THEN 0 ELSE ROUND(((MWD.NET_QT / TIM.TOTAL_INPUT_QT) * 100), 2) END AS TOTAL_YIELD,
                   NVL(TIM.START_MINUTE, 0) AS START_MINUTE, NVL(TIM.BASE_MINUTE, 0) AS BASE_MINUTE, NVL(TIM.GOOD_MINUTE, 0) AS GOOD_MINUTE,
                   NVL(TIM.WRK_MINUTE, 0) AS WRK_MINUTE, NVL(TIM.PRD_MINUTE, 0) AS PRD_MINUTE,
                   NVL(NOP.TOTAL_NOP_TIME, 0) AS TOTAL_NOP_TIME, NVL(NOP.NOP_TIME, 0) AS NOP_TIME, NVL(NOP.NCL_TIME, 0) AS NCL_TIME,
                   NVL(TIM.PRD_MINUTE, 0) + NVL(NOP.TOTAL_NOP_TIME, 0) AS RUN_TIME,
                   NVL(MEM.EMP_CNT, 0) AS EMP_CNT,
                   MITEM2.PPR_FG_CD, MC4.SYSDEF_NM AS PPR_FG_NM, PPI.MTRIL_CD, CITEM.ITEM_NM AS MTRIL_NM,
                   CASE WHEN UPPER(CITEM.STD_UNIT_CD) = 'R' THEN '시트지'
                        WHEN UPPER(CITEM.STD_UNIT_CD) = 'KG' THEN 'ROLL'
                        ELSE NULL END AS PPKD_NM2,
                   MITEM2.PPKD_CD, MC5.SYSDEF_NM AS PPKD_NM, MITEM2.PPKD_LCLAS_CD, MC6.SYSDEF_NM AS PPKD_LCLAS_NM,
                   MITEM2.BWEI_QT, MITEM2.HRZN_QT, MITEM2.VTCL_QT,
                   PPI.NET_QT AS NET_R, 'R' AS UNIT_CD, NVL(PED.INSL_QT, 0) AS INSL_QT, MWD.PAC_VR2,
                   CASE WHEN NVL(TIM.PRD_MINUTE, 0) = 0 THEN 0 ELSE ROUND(((MWD.WRK_QT / (TIM.PRD_MINUTE / 60))), 2) END AS TIME_PRD_QT,
                   CASE WHEN NVL(TIM.PRD_MINUTE, 0) = 0 THEN 0 ELSE ROUND((MWD.WRK_QT / TIM.PRD_MINUTE), 2) END AS WRK_LS,
                   TIM.ITEM_TYPE_NM,
                   ROUND(((NVL(MITEM2.BWEI_QT, 0) / 1000) * (NVL(MITEM2.HRZN_QT, 0) / 1000) * (NVL(MITEM2.VTCL_QT, 0) / 1000) * NVL(MWD.NET_QT, 0)), 2) AS WEIGHT_QT,
                   CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.WRK_QT / (PED.INSL_QT) * 60), 2) END AS STD_PRD_MINUTE,
                   CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.NET_QT / (PED.INSL_QT) * 60), 2) END AS STD_NET_MINUTE,
                   PPI.WRK_UM, PPI.WRK_AMT,
                   CITEM2.STD_LCLAS_CD, LCLAS.SYSDEF_NM AS STD_LCLAS_NM, CITEM2.STD_MLSFC_CD, MLSFC.SYSDEF_NM AS STD_MLSFC_NM,
                   CITEM2.STD_S_CSF_CD, SCSF.SYSDEF_NM AS STD_S_CSF_NM,
                   CASE WHEN NVL(TIM.WRK_MINUTE, 0) = 0 THEN 0 ELSE ROUND(((NVL(TIM.PRD_MINUTE, 0) / TIM.WRK_MINUTE) * 100), 2) END AS TIME_RATE,
                   CASE WHEN NVL(TIM.PRD_MINUTE, 0) = 0 THEN 0 ELSE ROUND((( CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.WRK_QT / (PED.INSL_QT) * 60), 2) END
                                                                            / TIM.PRD_MINUTE) * 100), 2) END AS PER_RATE,
                   CASE WHEN (CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.WRK_QT / (PED.INSL_QT) * 60), 2) END) = 0 THEN 0
                        ELSE ROUND((((CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.NET_QT / (PED.INSL_QT) * 60), 2) END)
                                   / (CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.WRK_QT / (PED.INSL_QT) * 60), 2) END)) * 100), 2)
                   END AS GOOD_RATE,
                   ROUND(((
                       CASE WHEN NVL(TIM.WRK_MINUTE, 0) = 0 THEN 0 ELSE ROUND(((NVL(TIM.PRD_MINUTE, 0) / TIM.WRK_MINUTE)), 2) END
                     * CASE WHEN NVL(TIM.PRD_MINUTE, 0) = 0 THEN 0 ELSE ROUND((( CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.WRK_QT / (PED.INSL_QT) * 60), 2) END
                                                                                / TIM.PRD_MINUTE)), 2) END
                     * CASE WHEN (CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.WRK_QT / (PED.INSL_QT) * 60), 2) END) = 0 THEN 0
                            ELSE ROUND((((CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.NET_QT / (PED.INSL_QT) * 60), 2) END)
                                       / (CASE WHEN NVL(PED.INSL_QT, 0) = 0 THEN 0 ELSE ROUND((MWD.WRK_QT / (PED.INSL_QT) * 60), 2) END))), 2)
                       END) * 100), 2) AS OEE
            FROM ME_WOCONF_DTL_X20329 MWD
            INNER JOIN MA_PLANT_MST MPM             ON MWD.COMPANY_CD = MPM.COMPANY_CD AND MWD.PLANT_CD = MPM.PLANT_CD
            """ + EQ_DTL_JOIN + """
            INNER JOIN PM_EQ_SDTL PES               ON MWD.COMPANY_CD = PES.COMPANY_CD AND MWD.EQP_CD = PES.EQP_CD AND PES.LANG_CD = 'KO'
            INNER JOIN PP_WRKGRP_INFO_X20329 PWI    ON MWD.COMPANY_CD = PWI.COMPANY_CD AND MWD.PLANT_CD = PWI.PLANT_CD AND MWD.EQP_CD = PWI.EQP_CD
            LEFT OUTER JOIN MA_CODEDTL MCOP         ON MCOP.COMPANY_CD = MWD.COMPANY_CD AND MCOP.MODULE_CD = 'PP' AND MCOP.FIELD_CD = 'Z005_20329' AND MCOP.SYSDEF_CD = PWI.UP_ORGN_CD
            LEFT OUTER JOIN MA_CODEDTL MC           ON MWD.COMPANY_CD = MC.COMPANY_CD AND MWD.SHIFT_CD = MC.SYSDEF_CD AND MC.MODULE_CD = 'ME' AND MC.FIELD_CD = 'P00520'
            INNER JOIN PP_PLANPRW_INFO_X20329 PPI   ON MWD.COMPANY_CD = PPI.COMPANY_CD AND MWD.PLANT_CD = PPI.PLANT_CD AND MWD.PLAN_NO = PPI.PLAN_NO
                                                   AND MWD.PLAN_HIS_SQ = PPI.PLAN_HIS_SQ AND MWD.PLAN_SQ = PPI.PLAN_SQ AND MWD.PLAN_LOW_SQ = PPI.PLAN_LOW_SQ
            INNER JOIN MA_ITEM MITEM                ON PPI.COMPANY_CD = MITEM.COMPANY_CD AND PPI.ITEM_CD = MITEM.ITEM_CD
            INNER JOIN ORDER_TEMP ORD               ON PPI.COMPANY_CD = ORD.COMPANY_CD AND PPI.PLANT_CD = ORD.PLANT_CD AND PPI.ORDDOC_NO = ORD.ORDDOC_NO AND PPI.ORDDOC_SQ = ORD.ORDDOC_SQ
            LEFT OUTER JOIN MA_CODEDTL MC2          ON MITEM.COMPANY_CD = MC2.COMPANY_CD AND MITEM.PRDUCTGRP_CD = MC2.SYSDEF_CD AND MC2.MODULE_CD = 'MA' AND MC2.FIELD_CD = 'S00020'
            LEFT OUTER JOIN ME_EQPDNBWRK_INFO_X20329 MEI ON MWD.COMPANY_CD = MEI.COMPANY_CD AND MWD.PLANT_CD = MEI.PLANT_CD AND MWD.EQP_CD = MEI.EQP_CD
                                                   AND MWD.SHIFT_CD = MEI.DN_FG AND MWD.WRK_DT = MEI.WRK_DT
            LEFT OUTER JOIN MA_CODEDTL MC3          ON PPI.COMPANY_CD = MC3.COMPANY_CD AND PPI.CONFIG_CD = MC3.SYSDEF_CD AND MC3.MODULE_CD = 'SD' AND MC3.FIELD_CD = 'Z007_20329'
            INNER JOIN TIME_PRD_TEMP TIM            ON MWD.COMPANY_CD = TIM.COMPANY_CD AND MWD.PLANT_CD = TIM.PLANT_CD AND MWD.WRK_CMPT_NO = TIM.WRK_CMPT_NO AND MWD.WRK_CMPT_SQ = TIM.WRK_CMPT_SQ
            LEFT OUTER JOIN NOP_TEMP NOP            ON MWD.COMPANY_CD = NOP.COMPANY_CD AND MWD.EQP_CD = NOP.EQP_CD AND MWD.WRK_CMPT_NO = NOP.PAC_VR1 AND MWD.WRK_CMPT_SQ = NOP.PAC_VR2
            LEFT OUTER JOIN CI_ITEM CITEM           ON PPI.MTRIL_CD = CITEM.ITEM_CD
            LEFT OUTER JOIN MA_ITEM_X20329 MITEM2   ON PPI.COMPANY_CD = MITEM2.COMPANY_CD AND PPI.MTRIL_CD = MITEM2.ITEM_CD
            LEFT OUTER JOIN MA_CODEDTL MC4          ON MITEM2.COMPANY_CD = MC4.COMPANY_CD AND MITEM2.PPR_FG_CD = MC4.SYSDEF_CD AND MC4.MODULE_CD = 'MA' AND MC4.FIELD_CD = 'Z005_20329'
            LEFT OUTER JOIN MA_CODEDTL MC5          ON MITEM2.COMPANY_CD = MC5.COMPANY_CD AND MITEM2.PPKD_CD = MC5.SYSDEF_CD AND MC5.MODULE_CD = 'MA' AND MC5.FIELD_CD = 'Z002_20329'
            LEFT OUTER JOIN MA_CODEDTL MC6          ON MITEM2.COMPANY_CD = MC6.COMPANY_CD AND MITEM2.PPKD_LCLAS_CD = MC6.SYSDEF_CD AND MC6.MODULE_CD = 'MA' AND MC6.FIELD_CD = 'Z001_20329'
            INNER JOIN CI_ITEM CITEM2               ON PPI.ITEM_CD = CITEM2.ITEM_CD
            LEFT OUTER JOIN CI_CODEDTL LCLAS        ON CITEM2.STD_LCLAS_CD = LCLAS.SYSDEF_CD AND LCLAS.MODULE_CD = 'MA' AND LCLAS.FIELD_CD = 'P00260'
            LEFT OUTER JOIN CI_CODEDTL MLSFC        ON CITEM2.STD_MLSFC_CD = MLSFC.SYSDEF_CD AND MLSFC.MODULE_CD = 'MA' AND MLSFC.FIELD_CD = 'P00680'
            LEFT OUTER JOIN CI_CODEDTL SCSF         ON CITEM2.STD_S_CSF_CD = SCSF.SYSDEF_CD AND SCSF.MODULE_CD = 'MA' AND SCSF.FIELD_CD = 'P00390'
            LEFT OUTER JOIN (
                SELECT MEM.COMPANY_CD, MEM.PLANT_CD, MEM.WRK_CMPT_NO, MEM.WRK_CMPT_SQ, COUNT(EMP_NO) AS EMP_CNT
                FROM ME_WOCONFEM_INFO_X20329 MEM
                INNER JOIN PP_WRKGRP_INFO_X20329 PWI ON MEM.COMPANY_CD = PWI.COMPANY_CD AND MEM.PLANT_CD = PWI.PLANT_CD AND MEM.OP_CD = PWI.OP_CD
                WHERE MEM.COMPANY_CD = '1000' AND MEM.PLANT_CD = '1000'
                AND   PWI.TOP_ORGN_CD = ?
                GROUP BY MEM.COMPANY_CD, MEM.PLANT_CD, MEM.WRK_CMPT_NO, MEM.WRK_CMPT_SQ
            ) MEM ON MWD.COMPANY_CD = MEM.COMPANY_CD AND MWD.PLANT_CD = MEM.PLANT_CD AND MWD.WRK_CMPT_NO = MEM.WRK_CMPT_NO AND MWD.WRK_CMPT_SQ = MEM.WRK_CMPT_SQ
            WHERE MWD.COMPANY_CD = '1000' AND MWD.PLANT_CD = '1000'
            AND   MWD.WRK_DT BETWEEN ? AND ?
            AND   PWI.TOP_ORGN_CD = ?
            ORDER BY MWD.EQP_CD, MWD.WRK_DT, MWD.ORDDOC_NO, MWD.PLAN_NO, PPI.CONFIG_CD, MWD.PRPCNT_SQ, MWD.PAC_VR1
            """;

    /**
     * @param workCenter 작업장 그룹(PP_WRKGRP_INFO_X20329.TOP_ORGN_CD) — 'WC20' 인쇄 / 'WC40' 제본(접지 제외).
     */
    public List<Map<String, Object>> findRows(LocalDate startDate, LocalDate endDate, String workCenter) {
        String s = startDate.format(BASIC);
        String e = endDate.format(BASIC);
        String wc = workCenter.trim();
        if ("WC40".equals(wc)) {
            // TIME_TEMP(s,e) · 본문(s,e)
            return jdbcTemplate.query(BIND_SQL, this::map, s, e, s, e);
        }
        // 바인딩 순서 = 쿼리에 나오는 순서: FIRST_AB(wc,s,e) · TOTAL_INPUT(s,e) · TIME_PRD(wc,s,e) · MEM(wc) · 본문(s,e,wc)
        return jdbcTemplate.query(SQL, this::map, wc, s, e, s, e, wc, s, e, wc, s, e, wc);
    }

    /**
     * 작업장 그룹의 설비 목록 — 가동 현황 보드가 실적이 없는 설비도 "대기"로 깔아 두기 위해 쓴다.
     * PP_WRKGRP_INFO_X20329(설비↔공정↔작업장) 에서 설비를 뽑고 이름은 PM_EQ_SDTL(KO).
     */
    /**
     * 등록은 돼 있지만 지금 안 쓰는 설비 — 가동 현황 보드에 "대기" 카드로 깔리지 않게 목록에서 뺀다(사용자 확인 2026-10-02).
     * 실적이 생기면 보드가 실적 쪽에서 설비를 다시 올리므로 실적 조회에는 영향 없다.
     *   T01W2O1-02 매엽2호기(마지막 실적 2025-03) · T01W2O4-01 디지털인쇄(실적 없음)
     *   T14W4O1-96 명지북(무선)(마지막 2026-06) · T01W4O5-01 재단기(실적 없음)
     */
    private static final String UNUSED_EQUIPMENTS = "'T01W2O1-02','T01W2O4-01','T14W4O1-96','T01W4O5-01'";

    public List<Map<String, Object>> findEquipments(String workCenter) {
        // 제본은 접지(OP406) 설비를 뺀다 — 실적 조회와 같은 범위
        String exclude = ("WC40".equals(workCenter.trim()) ? "AND PWI.UP_ORGN_CD <> 'OP406' " : "")
                + "AND PWI.EQP_CD NOT IN (" + UNUSED_EQUIPMENTS + ")";
        return jdbcTemplate.query("""
                SELECT PWI.EQP_CD, MAX(PES.EQP_NM) AS EQP_NM, MIN(PWI.UP_ORGN_CD) AS OP_CD, MAX(MC.SYSDEF_NM) AS OP_NM
                FROM PP_WRKGRP_INFO_X20329 PWI
                LEFT OUTER JOIN PM_EQ_SDTL PES ON PES.COMPANY_CD = PWI.COMPANY_CD AND PES.EQP_CD = PWI.EQP_CD AND PES.LANG_CD = 'KO'
                LEFT OUTER JOIN MA_CODEDTL MC  ON MC.COMPANY_CD = PWI.COMPANY_CD AND MC.MODULE_CD = 'PP' AND MC.FIELD_CD = 'Z005_20329' AND MC.SYSDEF_CD = PWI.UP_ORGN_CD
                WHERE PWI.COMPANY_CD = '1000' AND PWI.PLANT_CD = '1000' AND PWI.TOP_ORGN_CD = ?
                """ + exclude + """
                GROUP BY PWI.EQP_CD
                ORDER BY PWI.EQP_CD
                """, this::map, workCenter.trim());
    }

    /** 컬럼명(UPPER_SNAKE) → camelCase 키. 값은 드라이버 타입 그대로(NUMBER → BigDecimal, 문자열은 trim). */
    private Map<String, Object> map(ResultSet rs, int i) throws SQLException {
        ResultSetMetaData md = rs.getMetaData();
        Map<String, Object> row = new LinkedHashMap<>();
        for (int c = 1; c <= md.getColumnCount(); c++) {
            Object v = rs.getObject(c);
            if (v instanceof String str) v = str.trim();
            row.put(camel(md.getColumnLabel(c)), v);
        }
        return row;
    }

    static String camel(String upperSnake) {
        StringBuilder sb = new StringBuilder();
        boolean up = false;
        for (char ch : upperSnake.toLowerCase().toCharArray()) {
            if (ch == '_') { up = true; continue; }
            sb.append(up ? Character.toUpperCase(ch) : ch);
            up = false;
        }
        return sb.toString();
    }
}
