package com.tara.crm.stats.repository;

import com.tara.crm.stats.dto.PodProductionDto;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.boot.autoconfigure.condition.ConditionalOnProperty;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Repository;

import java.math.BigDecimal;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import java.util.List;

/**
 * POD 생산내역 — 더존 iCUBE 정본 MAPPIR00400_Z20329(listMst/listDtl)을 그대로 옮긴 것.
 * CTE 없이 직접 조인(정본 구조 동일). 무거운 금액집계(SU_AMT) 서브쿼리에 기간필터를 밀어넣어 스코프를 좁힌다.
 * 조판 나눗셈 가드만 정본의 TO_NUMBER(...) IS NOT NULL 대신 REGEXP_LIKE 로 대체(비숫자 ETC_DC3에서 ORA-01722 방지, 숫자면 결과 동일).
 */
@Repository
@RequiredArgsConstructor
@ConditionalOnProperty(name = "oracle.enabled", havingValue = "true")
public class OraclePodProductionRepository {

    @Qualifier("oracleJdbcTemplate")
    private final JdbcTemplate jdbcTemplate;
    private static final DateTimeFormatter BASIC = DateTimeFormatter.BASIC_ISO_DATE;

    public List<PodProductionDto.Row> findRows(LocalDate startDate, LocalDate endDate,
                                                String workPlaceCd, String itemType,
                                                String salesDepartmentCd, String salesEmployee,
                                                String keyword) {
        String startStr = startDate.format(BASIC);
        String endStr = endDate.plusDays(1).format(BASIC);
        StringBuilder sql = new StringBuilder("""
            SELECT DISTINCT
                   SOD.PRPL_CD, MC_PRPL.SYSDEF_NM AS PRPL_NM,
                   SOD.ORDDOC_NO, SOD.ORDDOC_SQ, SOM.ORDDOC_NM,
                   CASE WHEN LENGTH(TRIM(SOM.ORD_DT)) = 8
                        THEN SUBSTR(TRIM(SOM.ORD_DT),1,4)||'-'||SUBSTR(TRIM(SOM.ORD_DT),5,2)||'-'||SUBSTR(TRIM(SOM.ORD_DT),7,2)
                        ELSE TRIM(SOM.ORD_DT) END AS ORD_DT,
                   SOM.DEPT_CD AS SALES_DEPT_CD, SALES_DEPT.DEPT_NM AS SALES_DEPT_NM,
                   HEM.KOR_NM AS BIZRSPT_EMPNO_NM, MC_ITEMFG.SYSDEF_NM AS ITEM_FG,
                   SOD.ITEM_CD, SOD.ITEM_NM, SOD.SPCFCS_ITEM_NM, SOD.ORD_QT,
                   NVL(SOI.PAGE_QT, 1) AS PAGE_QT,
                   DECODE(NVL(SOD.ETC_DC3, 0), 0, 1, SOD.ETC_DC3) AS ETC_DC3,
                   ROUND(NVL(SOI.PAGE_QT,1) / DECODE(NVL(SOD.ETC_DC3,0),0,1,SOD.ETC_DC3)) AS TOTAL_PAGE_QT,
                   SU_AMT.SUM_AMT, SOD.HRZN_QT||'*'||SOD.VTCL_QT AS SIZE_QT,
                   MC_PACK.SYSDEF_NM AS PACK_MTHD_NM,
                   CASE WHEN SOD.ETC_DC='1' THEN '머리-머리' WHEN SOD.ETC_DC='2' THEN '머리-꼬리' ELSE '' END AS PRINT_DIRECTION,
                   TO_CHAR(SOD.DLVSH_DTS,'YYYY/MM/DD HH24:MI') AS DLVSH_DTS,
                   HEM2.KOR_NM AS PP_ASGNR_NM,
                   NVL(MC_PRST.SYSDEF_NM,'접수대기') AS PRGR_ST,
                   CASE WHEN POD.PRGR_ST='600' THEN TO_CHAR(POD.WRK_DTS6,'YYYY/MM/DD HH24:MI') ELSE '작업중' END AS WRK_DTS
              FROM SD_ORDER_MST_X20329 SOM
              INNER JOIN SD_ORDER_DTL_X20329 SOD ON SOM.COMPANY_CD=SOD.COMPANY_CD AND SOM.ORDDOC_NO=SOD.ORDDOC_NO
              LEFT JOIN (
                    SELECT SOIX.ORDDOC_NO, SOIX.ORDDOC_SQ,
                           ROUND(SUM(CASE WHEN SOIX.UP_ORGN_CD IN ('OP601','OP602','OP603')
                                THEN NVL(SOIX.PAGE_QT,1)*NVL(SOIX.ORD_QT,1) ELSE 0 END),2) AS PAGE_QT
                      FROM SD_ORDDIG_INFO_X20329 SOIX
                      JOIN SD_ORDER_MST_X20329 SOMPG ON SOIX.COMPANY_CD=SOMPG.COMPANY_CD AND SOIX.ORDDOC_NO=SOMPG.ORDDOC_NO
                     WHERE SOIX.COMPANY_CD='1000' AND SOIX.PLAN_PLANT_CD='2000'
                       AND NVL(SOIX.ETC_DC,'N') NOT IN ('Y','P')
                       AND SOMPG.ORD_DT >= ? AND SOMPG.ORD_DT < ?
                     GROUP BY SOIX.ORDDOC_NO, SOIX.ORDDOC_SQ
              ) SOI ON SOI.ORDDOC_NO=SOD.ORDDOC_NO AND SOI.ORDDOC_SQ=SOD.ORDDOC_SQ
              LEFT JOIN MA_CODEDTL MC_PRPL ON MC_PRPL.COMPANY_CD=SOD.COMPANY_CD AND MC_PRPL.MODULE_CD='SD' AND MC_PRPL.FIELD_CD='Z021_20329' AND MC_PRPL.SYSDEF_CD=SOD.PRPL_CD
              LEFT JOIN MA_CODEDTL MC_ITEMFG ON MC_ITEMFG.COMPANY_CD=SOM.COMPANY_CD AND MC_ITEMFG.MODULE_CD='SD' AND MC_ITEMFG.FIELD_CD='Z004_20329' AND MC_ITEMFG.SYSDEF_CD=SOD.ITEM_FG
              LEFT JOIN MA_CODEDTL MC_PACK ON MC_PACK.COMPANY_CD=SOD.COMPANY_CD AND MC_PACK.MODULE_CD='SD' AND MC_PACK.FIELD_CD='Z023_20329' AND MC_PACK.SYSDEF_CD=SOD.PACK_MTHD_CD
              LEFT JOIN HR_EMP_MST HEM ON HEM.COMPANY_CD=SOM.COMPANY_CD AND HEM.EMP_NO=SOM.BIZRSPT_EMPNO_CD
              LEFT JOIN VW_MA_DEPT_MST SALES_DEPT ON SALES_DEPT.COMPANY_CD=SOM.COMPANY_CD AND SALES_DEPT.DEPT_CD=SOM.DEPT_CD
              LEFT JOIN PP_ORDPOD_DTL_X20329 POD ON POD.COMPANY_CD=SOD.COMPANY_CD AND POD.ORDDOC_NO=SOD.ORDDOC_NO AND POD.ORDDOC_SQ=SOD.ORDDOC_SQ
              LEFT JOIN HR_EMP_MST HEM2 ON HEM2.COMPANY_CD=POD.COMPANY_CD AND HEM2.EMP_NO=POD.ASGNR_NO
              LEFT JOIN MA_CODEDTL MC_PRST ON MC_PRST.COMPANY_CD=POD.COMPANY_CD AND MC_PRST.MODULE_CD='PP' AND MC_PRST.FIELD_CD='Z017_20329' AND MC_PRST.SYSDEF_CD=POD.PRGR_ST
              INNER JOIN (
                    SELECT SOI.ORDDOC_NO, SOI.ORDDOC_SQ,
                           SUM(ROUND(CASE
                             WHEN SOI.ITEM_CD IN ('G13A002001') AND SOI.WRK_CD IN ('60101','60102','60103') AND SOI.MTRIL_CD IS NULL THEN
                               (CEIL((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT) / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END)*2
                                * CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                             WHEN SOI.ITEM_CD IN ('G13A002001') AND CI2.ITEM_DTL_SPEC_DC IN ('520*330') THEN
                               (CEIL((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT) / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END)*2
                                * CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                             WHEN SOI.ITEM_CD IN ('G13A002001') AND CI2.ITEM_DTL_SPEC_DC IN ('466*315') THEN
                               (CEIL((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT) / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END)
                                * CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                             WHEN SOI.ITEM_CD IN ('G13A002001') AND SOI.WRK_CD IN ('70603') THEN
                               (CEIL((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT) / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END)
                                * CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                             WHEN SOI.CONFIG_CD IN ('60102','60104','60106') THEN
                               (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                                * CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                                / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END
                             WHEN SOI.CONFIG_CD IN ('60101','60103') THEN
                               (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                                * CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                             WHEN SOI.ITEM_CD='G12A001001' AND SOI.WRK_CD IN ('70102','70103','70104') THEN
                               (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT * 4.5)
                             WHEN SOI.WRK_CD IN ('70102','70103') AND SOI.OPT_DC IN ('10101','10104') THEN
                               (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                                * (CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                                / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END)
                             WHEN SOI.WRK_CD IN ('70102','70103') AND SOI.OPT_DC IN ('10105','10106') THEN
                               (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                                * (CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END))
                             WHEN SOI.ITEM_CD='G12A001001' AND SOI.WRK_CD IN ('70602') THEN
                               (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT * 10)
                             WHEN SOI.WRK_CD IN ('70601') THEN
                               CEIL((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT) / 250.0) * 300
                             WHEN SOI.WRK_CD IN ('70801') AND SOI.OPT_DC IN ('11202','11201') AND SOI.OPT_DC2 IN ('20502') THEN
                               (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                               * ((COALESCE(SOD.HRZN_QT,1)/1000)*2*CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                             WHEN SOI.WRK_CD IN ('70801') AND SOI.OPT_DC IN ('11202','11201') AND SOI.OPT_DC2 IN ('20503') THEN
                               (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                               * ((COALESCE(SOD.VTCL_QT,1)/1000)*2*CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                             WHEN SOI.WRK_CD IN ('70801') AND SOI.OPT_DC IN ('11202','11201') AND SOI.OPT_DC2 IN ('20507','20508') THEN
                               (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                               * ((COALESCE(SOD.HRZN_QT,1)/1000)*CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                             WHEN SOI.WRK_CD IN ('70801') AND SOI.OPT_DC IN ('11202','11201') AND SOI.OPT_DC2 IN ('20509','20510') THEN
                               (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                               * ((COALESCE(SOD.VTCL_QT,1)/1000)*CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                             WHEN SOI.WRK_CD IN ('70801') AND SOI.OPT_DC IN ('11202','11201') AND SOI.OPT_DC2 IN ('20501') THEN
                               (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                               * (((COALESCE(SOD.HRZN_QT,1)/1000)*2*CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                               + ((COALESCE(SOD.VTCL_QT,1)/1000)*2*CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END))
                             WHEN SOI.WRK_CD IN ('70811') AND SOI.OPT_DC IN ('10909','10910') THEN
                               ((COALESCE(SOD.HRZN_QT,1)/1000)*CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                               * (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                             WHEN SOI.WRK_CD IN ('70811') AND SOI.OPT_DC IN ('10913') THEN
                               ((COALESCE(SOD.HRZN_QT,1)/1000)*2*CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                               * (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                             WHEN SOI.WRK_CD IN ('60201','60202','60203','60204','60206','60301','60302','60303','60304','60305','60306','70804','70201','70806','70901','70902','70903','70904','70905') THEN
                               (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                                * CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                               * COALESCE(SOD.HRZN_QT,1)/1000 * COALESCE(SOD.VTCL_QT,1)/1000
                             WHEN SOI.UP_ORGN_CD IN ('OP903','OP904','OP905','OP906','OP907') THEN
                               ((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                                * CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                                * COALESCE(SOD.HRZN_QT,1)/1000 * COALESCE(SOD.VTCL_QT,1)/1000)
                               + CASE WHEN (COALESCE(SOD.HRZN_QT,1)/1000 * COALESCE(SOD.VTCL_QT,1)/1000) <= 0.25 THEN COALESCE(POI.MIN_VAL_AMT1,0) ELSE 0 END
                             ELSE
                               CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END
                               * CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                           END,0)) AS SUM_AMT
                      FROM SD_ORDDIG_INFO_X20329 SOI
                      INNER JOIN SD_ORDER_DTL_X20329 SOD ON SOI.COMPANY_CD=SOD.COMPANY_CD AND SOI.ORDDOC_NO=SOD.ORDDOC_NO AND SOI.ORDDOC_SQ=SOD.ORDDOC_SQ
                      INNER JOIN SD_ORDER_MST_X20329 SOM ON SOI.COMPANY_CD=SOM.COMPANY_CD AND SOI.ORDDOC_NO=SOM.ORDDOC_NO
                      LEFT JOIN MA_CODEDTL MC ON SOD.COMPANY_CD=MC.COMPANY_CD AND SOD.PRPL_CD=MC.SYSDEF_CD AND MC.MODULE_CD='SD' AND MC.FIELD_CD='Z021_20329'
                      LEFT JOIN CI_ITEM CI2 ON SOI.MTRIL_CD=CI2.ITEM_CD
                      LEFT JOIN PP_OPTPRI_INFO_X20329 POI ON SOI.COMPANY_CD=POI.COMPANY_CD AND SOI.PLAN_PLANT_CD=POI.PLANT_CD AND SOI.WRK_CD=POI.WRK_CD AND SOI.UP_ORGN_CD=POI.UP_ORGN_CD AND SOI.CONFIG_CD=POI.CONFIG_CD AND COALESCE(SOI.OPT_DC,'X')=POI.OPT_CD1 AND COALESCE(SOI.OPT_DC2,'X')=POI.OPT_CD2 AND COALESCE(SOI.OPT_DC3,'X')=POI.OPT_CD3 AND COALESCE(SOI.OPT_DC4,'X')=POI.OPT_CD4 AND COALESCE(SOI.OPT_DC5,'X')=POI.OPT_CD5
                       AND NVL(POI.USE_YN,'Y')='Y'
                       -- 특례: 영업거래처 00937 주문은 단가를 거래처 P34156로 등록된 것으로 조회(없는 사양은 공통단가 폴백)
                       AND ((POI.PARTNER_CD_USE_YN='Y' AND TRIM(POI.PARTNER_CD)=(CASE WHEN TRIM(SOM.PARTNER_CD)='00937' THEN 'P34156' ELSE TRIM(SOM.PARTNER_CD) END))
                         OR (NVL(POI.PARTNER_CD_USE_YN,'N')='N' AND NOT EXISTS (
                              SELECT 1 FROM PP_OPTPRI_INFO_X20329 P_SPEC
                               WHERE P_SPEC.COMPANY_CD=POI.COMPANY_CD AND P_SPEC.PLANT_CD=POI.PLANT_CD
                                 AND P_SPEC.WRK_CD=POI.WRK_CD AND P_SPEC.UP_ORGN_CD=POI.UP_ORGN_CD
                                 AND P_SPEC.CONFIG_CD=POI.CONFIG_CD
                                 AND P_SPEC.OPT_CD1=POI.OPT_CD1 AND P_SPEC.OPT_CD2=POI.OPT_CD2
                                 AND P_SPEC.OPT_CD3=POI.OPT_CD3 AND P_SPEC.OPT_CD4=POI.OPT_CD4 AND P_SPEC.OPT_CD5=POI.OPT_CD5
                                 AND P_SPEC.PARTNER_CD_USE_YN='Y' AND TRIM(P_SPEC.PARTNER_CD)=(CASE WHEN TRIM(SOM.PARTNER_CD)='00937' THEN 'P34156' ELSE TRIM(SOM.PARTNER_CD) END)
                                 AND NVL(P_SPEC.USE_YN,'Y')='Y')))
                     WHERE SOI.COMPANY_CD='1000' AND SOM.PLAN_PLANT_CD='2000'
                       AND NVL(SOI.ETC_DC,'N') NOT IN ('Y','P')
                       AND SOM.ORD_DT >= ? AND SOM.ORD_DT < ?
                     GROUP BY SOI.ORDDOC_NO, SOI.ORDDOC_SQ
              ) SU_AMT ON SU_AMT.ORDDOC_NO=SOD.ORDDOC_NO AND SU_AMT.ORDDOC_SQ=SOD.ORDDOC_SQ
             WHERE SOM.COMPANY_CD='1000' AND SOM.PLAN_PLANT_CD='2000'
               AND SOM.PRW_FG='1'
               AND SOD.ORDDOC_ST='1'
               AND SOD.PRPL_CD NOT IN ('G9999','G0601','G0600')
               AND (POD.PRGR_ST IS NULL OR POD.PRGR_ST NOT IN ('700','001'))
               AND MC_ITEMFG.REL_FLAG_5_CD='1'
               AND SOM.ORD_DT >= ? AND SOM.ORD_DT < ?
            """);
        List<Object> params = new ArrayList<>();
        params.add(startStr); params.add(endStr);   // 총페이지 서브쿼리 기간
        params.add(startStr); params.add(endStr);   // SU_AMT 서브쿼리 기간
        params.add(startStr); params.add(endStr);   // 외부 목록 기간
        if (hasText(workPlaceCd)) { sql.append(" AND SOD.PRPL_CD=?"); params.add(workPlaceCd); }
        if (hasText(itemType)) { sql.append(" AND MC_ITEMFG.SYSDEF_NM=?"); params.add(itemType); }
        if (hasText(salesDepartmentCd)) { sql.append(" AND SOM.DEPT_CD=?"); params.add(salesDepartmentCd); }
        if (hasText(salesEmployee)) { sql.append(" AND UPPER(HEM.KOR_NM) LIKE UPPER(?)"); params.add("%" + salesEmployee.trim() + "%"); }
        if (hasText(keyword)) {
            sql.append(" AND (UPPER(SOD.ORDDOC_NO) LIKE UPPER(?) OR UPPER(SOM.ORDDOC_NM) LIKE UPPER(?))");
            for (int i=0; i<2; i++) params.add("%" + keyword.trim() + "%");
        }
        sql.append(" ORDER BY SOD.ORDDOC_NO DESC, SOD.ORDDOC_SQ");
        return jdbcTemplate.query(sql.toString(), this::mapRow, params.toArray());
    }

    public List<PodProductionDto.Detail> findDetails(String orderNo, int orderSq) {
        // 정본 listDtl 동일. 옵션3~5 표시매핑(MC6~MC8)은 정본 그대로(OPT_DC2/3/4 참조 — 정본에 한 칸 밀린 흔적이 있으나 ERP 화면과 일치시키기 위해 미러링).
        String sql = """
            SELECT MC1.SYSDEF_NM AS PROCESS_NM, MC2.SYSDEF_NM AS CONFIG_NM, MC3.SYSDEF_NM AS WORK_NM,
                   NVL(MC9.SYSDEF_NM,'N') AS WORK_PLACE_NM,
                   MC4.SYSDEF_NM AS OPT1, MC5.SYSDEF_NM AS OPT2, MC6.SYSDEF_NM AS OPT3,
                   MC7.SYSDEF_NM AS OPT4, MC8.SYSDEF_NM AS OPT5,
                   SOI.MTRIL_CD, CI2.ITEM_NM AS MTRIL_NM, SOD.ORD_QT,
                   CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END AS PAGE_QT,
                   CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END AS UNIT_PRICE,
                   ROUND(CASE
                     WHEN SOI.ITEM_CD IN ('G13A002001') AND SOI.WRK_CD IN ('60101','60102','60103') AND SOI.MTRIL_CD IS NULL THEN
                       (CEIL((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT) / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END)*2
                        * CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.ITEM_CD IN ('G13A002001') AND CI2.ITEM_DTL_SPEC_DC IN ('520*330') THEN
                       (CEIL((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT) / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END)*2
                        * CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.ITEM_CD IN ('G13A002001') AND CI2.ITEM_DTL_SPEC_DC IN ('466*315') THEN
                       (CEIL((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT) / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END)
                        * CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.ITEM_CD IN ('G13A002001') AND SOI.WRK_CD IN ('70603') THEN
                       (CEIL((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT) / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END)
                        * CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.CONFIG_CD IN ('60102','60104','60106') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                        * CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                        / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END
                     WHEN SOI.CONFIG_CD IN ('60101','60103') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                        * CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.ITEM_CD='G12A001001' AND SOI.WRK_CD IN ('70102','70103','70104') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT * 4.5)
                     WHEN SOI.WRK_CD IN ('70102','70103') AND SOI.OPT_DC IN ('10101','10104') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                        * (CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                        / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END)
                     WHEN SOI.WRK_CD IN ('70102','70103') AND SOI.OPT_DC IN ('10105','10106') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                        * (CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END))
                     WHEN SOI.ITEM_CD='G12A001001' AND SOI.WRK_CD IN ('70602') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT * 10)
                     WHEN SOI.WRK_CD IN ('70601') THEN
                       CEIL((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT) / 250.0) * 300
                     WHEN SOI.WRK_CD IN ('70801') AND SOI.OPT_DC IN ('11202','11201') AND SOI.OPT_DC2 IN ('20502') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                       * ((COALESCE(SOD.HRZN_QT,1)/1000)*2*CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.WRK_CD IN ('70801') AND SOI.OPT_DC IN ('11202','11201') AND SOI.OPT_DC2 IN ('20503') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                       * ((COALESCE(SOD.VTCL_QT,1)/1000)*2*CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.WRK_CD IN ('70801') AND SOI.OPT_DC IN ('11202','11201') AND SOI.OPT_DC2 IN ('20507','20508') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                       * ((COALESCE(SOD.HRZN_QT,1)/1000)*CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.WRK_CD IN ('70801') AND SOI.OPT_DC IN ('11202','11201') AND SOI.OPT_DC2 IN ('20509','20510') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                       * ((COALESCE(SOD.VTCL_QT,1)/1000)*CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.WRK_CD IN ('70801') AND SOI.OPT_DC IN ('11202','11201') AND SOI.OPT_DC2 IN ('20501') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                       * (((COALESCE(SOD.HRZN_QT,1)/1000)*2*CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                       + ((COALESCE(SOD.VTCL_QT,1)/1000)*2*CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END))
                     WHEN SOI.WRK_CD IN ('70811') AND SOI.OPT_DC IN ('10909','10910') THEN
                       ((COALESCE(SOD.HRZN_QT,1)/1000)*CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                       * (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                     WHEN SOI.WRK_CD IN ('70811') AND SOI.OPT_DC IN ('10913') THEN
                       ((COALESCE(SOD.HRZN_QT,1)/1000)*2*CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                       * (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                     WHEN SOI.WRK_CD IN ('60201','60202','60203','60204','60206','60301','60302','60303','60304','60305','60306','70804','70201','70806','70901','70902','70903','70904','70905') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                        * CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                       * COALESCE(SOD.HRZN_QT,1)/1000 * COALESCE(SOD.VTCL_QT,1)/1000
                     WHEN SOI.UP_ORGN_CD IN ('OP903','OP904','OP905','OP906','OP907') THEN
                       ((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                        * CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                        * COALESCE(SOD.HRZN_QT,1)/1000 * COALESCE(SOD.VTCL_QT,1)/1000)
                       + CASE WHEN (COALESCE(SOD.HRZN_QT,1)/1000 * COALESCE(SOD.VTCL_QT,1)/1000) <= 0.25 THEN COALESCE(POI.MIN_VAL_AMT1,0) ELSE 0 END
                     ELSE
                       CASE WHEN COALESCE(MC9.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END
                       * CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                   END,0) AS SUM_AMT,
                   SOD.HRZN_QT||'*'||SOD.VTCL_QT AS SIZE_QT, SOI.RMK_TXT
              FROM SD_ORDDIG_INFO_X20329 SOI
              INNER JOIN SD_ORDER_DTL_X20329 SOD ON SOI.COMPANY_CD=SOD.COMPANY_CD AND SOI.ORDDOC_NO=SOD.ORDDOC_NO AND SOI.ORDDOC_SQ=SOD.ORDDOC_SQ
              INNER JOIN SD_ORDER_MST_X20329 SOM ON SOI.COMPANY_CD=SOM.COMPANY_CD AND SOI.ORDDOC_NO=SOM.ORDDOC_NO
              LEFT JOIN PP_OPTPRI_INFO_X20329 POI ON SOI.COMPANY_CD=POI.COMPANY_CD AND SOI.PLAN_PLANT_CD=POI.PLANT_CD AND SOI.WRK_CD=POI.WRK_CD AND SOI.UP_ORGN_CD=POI.UP_ORGN_CD AND SOI.CONFIG_CD=POI.CONFIG_CD AND COALESCE(SOI.OPT_DC,'X')=POI.OPT_CD1 AND COALESCE(SOI.OPT_DC2,'X')=POI.OPT_CD2 AND COALESCE(SOI.OPT_DC3,'X')=POI.OPT_CD3 AND COALESCE(SOI.OPT_DC4,'X')=POI.OPT_CD4 AND COALESCE(SOI.OPT_DC5,'X')=POI.OPT_CD5
               AND NVL(POI.USE_YN,'Y')='Y'
               AND ((POI.PARTNER_CD_USE_YN='Y' AND TRIM(POI.PARTNER_CD)=(CASE WHEN TRIM(SOM.PARTNER_CD)='00937' THEN 'P34156' ELSE TRIM(SOM.PARTNER_CD) END))
                 OR (NVL(POI.PARTNER_CD_USE_YN,'N')='N' AND NOT EXISTS (
                      SELECT 1 FROM PP_OPTPRI_INFO_X20329 P_SPEC
                       WHERE P_SPEC.COMPANY_CD=POI.COMPANY_CD AND P_SPEC.PLANT_CD=POI.PLANT_CD
                         AND P_SPEC.WRK_CD=POI.WRK_CD AND P_SPEC.UP_ORGN_CD=POI.UP_ORGN_CD
                         AND P_SPEC.CONFIG_CD=POI.CONFIG_CD
                         AND P_SPEC.OPT_CD1=POI.OPT_CD1 AND P_SPEC.OPT_CD2=POI.OPT_CD2
                         AND P_SPEC.OPT_CD3=POI.OPT_CD3 AND P_SPEC.OPT_CD4=POI.OPT_CD4 AND P_SPEC.OPT_CD5=POI.OPT_CD5
                         AND P_SPEC.PARTNER_CD_USE_YN='Y' AND TRIM(P_SPEC.PARTNER_CD)=(CASE WHEN TRIM(SOM.PARTNER_CD)='00937' THEN 'P34156' ELSE TRIM(SOM.PARTNER_CD) END)
                         AND NVL(P_SPEC.USE_YN,'Y')='Y')))
              LEFT JOIN CI_ITEM CI2 ON CI2.ITEM_CD=SOI.MTRIL_CD
              LEFT JOIN MA_CODEDTL MC1 ON MC1.COMPANY_CD=SOI.COMPANY_CD AND MC1.MODULE_CD='PP' AND MC1.FIELD_CD='Z005_20329' AND MC1.SYSDEF_CD=SOI.UP_ORGN_CD
              LEFT JOIN MA_CODEDTL MC2 ON MC2.COMPANY_CD=SOI.COMPANY_CD AND MC2.MODULE_CD='SD' AND MC2.FIELD_CD='Z019_20329' AND MC2.SYSDEF_CD=SOI.CONFIG_CD
              LEFT JOIN MA_CODEDTL MC3 ON MC3.COMPANY_CD=SOI.COMPANY_CD AND MC3.MODULE_CD='SD' AND MC3.FIELD_CD='Z010_20329' AND MC3.SYSDEF_CD=SOI.WRK_CD
              LEFT JOIN MA_CODEDTL MC4 ON MC4.COMPANY_CD=SOI.COMPANY_CD AND MC4.MODULE_CD='PP' AND MC4.FIELD_CD='Z009_20329' AND MC4.SYSDEF_CD=SOI.OPT_DC
              LEFT JOIN MA_CODEDTL MC5 ON MC5.COMPANY_CD=SOI.COMPANY_CD AND MC5.MODULE_CD='PP' AND MC5.FIELD_CD='Z010_20329' AND MC5.SYSDEF_CD=SOI.OPT_DC2
              LEFT JOIN MA_CODEDTL MC6 ON MC6.COMPANY_CD=SOI.COMPANY_CD AND MC6.MODULE_CD='PP' AND MC6.FIELD_CD='Z011_20329' AND MC6.SYSDEF_CD=SOI.OPT_DC2
              LEFT JOIN MA_CODEDTL MC7 ON MC7.COMPANY_CD=SOI.COMPANY_CD AND MC7.MODULE_CD='PP' AND MC7.FIELD_CD='Z012_20329' AND MC7.SYSDEF_CD=SOI.OPT_DC3
              LEFT JOIN MA_CODEDTL MC8 ON MC8.COMPANY_CD=SOI.COMPANY_CD AND MC8.MODULE_CD='PP' AND MC8.FIELD_CD='Z013_20329' AND MC8.SYSDEF_CD=SOI.OPT_DC4
              LEFT JOIN MA_CODEDTL MC9 ON SOD.COMPANY_CD=MC9.COMPANY_CD AND SOD.PRPL_CD=MC9.SYSDEF_CD AND MC9.MODULE_CD='SD' AND MC9.FIELD_CD='Z021_20329'
             WHERE SOI.COMPANY_CD='1000' AND SOI.ORDDOC_NO=? AND SOI.ORDDOC_SQ=?
               AND NVL(SOI.ETC_DC,'N') NOT IN ('Y','P')
             ORDER BY SOI.LINE_SQ
            """;
        return jdbcTemplate.query(sql, (rs, rowNum) -> PodProductionDto.Detail.builder()
                .process(rs.getString("PROCESS_NM")).composition(rs.getString("CONFIG_NM"))
                .workMethod(rs.getString("WORK_NM")).workPlace(rs.getString("WORK_PLACE_NM"))
                .option1(rs.getString("OPT1")).option2(rs.getString("OPT2")).option3(rs.getString("OPT3"))
                .option4(rs.getString("OPT4")).option5(rs.getString("OPT5"))
                .materialCd(rs.getString("MTRIL_CD")).materialName(rs.getString("MTRIL_NM"))
                .quantity(decimal(rs,"ORD_QT")).pages(decimal(rs,"PAGE_QT"))
                .unitPrice(decimal(rs,"UNIT_PRICE")).amount(decimal(rs,"SUM_AMT"))
                .size(rs.getString("SIZE_QT")).remark(rs.getString("RMK_TXT")).build(), orderNo, orderSq);
    }

    /** POD 전체 작업사양(주문일 기준 flat) — GRP생산내역 하단을 기간 전체로 펼침. 작업처 G0500만.
     *  금액(SAL_AMT)·단가(UNIT_AMT)는 findRows/findDetails 와 동일 계산식 + USE_YN + 거래처단가 특례(00937→P34156). */
    public List<PodProductionDto.SpecRow> findAllSpecs(LocalDate startDate, LocalDate endDate) {
        String startStr = startDate.format(BASIC);
        String endStr = endDate.plusDays(1).format(BASIC);
        String sql = """
            SELECT
                   SOI.ORDDOC_NO, SOI.ORDDOC_SQ, SOI.LINE_SQ,
                   CASE WHEN LENGTH(TRIM(SOM.ORD_DT))=8
                        THEN SUBSTR(TRIM(SOM.ORD_DT),1,4)||'-'||SUBSTR(TRIM(SOM.ORD_DT),5,2)||'-'||SUBSTR(TRIM(SOM.ORD_DT),7,2)
                        ELSE TRIM(SOM.ORD_DT) END AS ORD_DT,
                   SOM.DEPT_CD, MDM.DEPT_NM,
                   NVL(POD.PRGR_ST,'000') AS PRGR_ST,
                   NVL(NULLIF(TRIM(MC2.SYSDEF_NM),''),'생산중') AS PRGR_ST_NM,
                   SOI.ITEM_CD,
                   SOI.WRK_CD, A.SYSDEF_NM AS WRK_NM,
                   SOI.CONFIG_CD, C.SYSDEF_NM AS CONFIG_NM,
                   SOI.OPT_DC, B.SYSDEF_NM AS OPT1_NM,
                   SOI.OPT_DC2, D.SYSDEF_NM AS OPT2_NM,
                   SOD.PRPL_CD, MC.SYSDEF_NM AS PRPL_NM,
                   COALESCE(MC.FLAG_CD,'N') AS WC_FG,
                   SOD.HRZN_QT, SOD.VTCL_QT,
                   CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END AS PAGE_QT,
                   SOD.ETC_DC3, SOI.ORD_QT,
                   CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END AS UNIT_AMT,
                   ROUND(CASE
                     WHEN SOI.ITEM_CD IN ('G13A002001') AND SOI.WRK_CD IN ('60101','60102','60103') AND SOI.MTRIL_CD IS NULL THEN
                       (CEIL((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT) / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END)*2
                        * CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.ITEM_CD IN ('G13A002001') AND CI2.ITEM_DTL_SPEC_DC IN ('520*330') THEN
                       (CEIL((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT) / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END)*2
                        * CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.ITEM_CD IN ('G13A002001') AND CI2.ITEM_DTL_SPEC_DC IN ('466*315') THEN
                       (CEIL((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT) / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END)
                        * CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.ITEM_CD IN ('G13A002001') AND SOI.WRK_CD IN ('70603') THEN
                       (CEIL((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT) / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END)
                        * CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.CONFIG_CD IN ('60102','60104','60106') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                        * CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                        / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END
                     WHEN SOI.CONFIG_CD IN ('60101','60103') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                        * CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.ITEM_CD='G12A001001' AND SOI.WRK_CD IN ('70102','70103','70104') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT * 4.5)
                     WHEN SOI.WRK_CD IN ('70102','70103') AND SOI.OPT_DC IN ('10101','10104') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                        * (CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                        / CASE WHEN REGEXP_LIKE(SOD.ETC_DC3,'^\\d+$') THEN TO_NUMBER(SOD.ETC_DC3) ELSE 1 END)
                     WHEN SOI.WRK_CD IN ('70102','70103') AND SOI.OPT_DC IN ('10105','10106') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                        * (CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END))
                     WHEN SOI.ITEM_CD='G12A001001' AND SOI.WRK_CD IN ('70602') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT * 10)
                     WHEN SOI.WRK_CD IN ('70601') THEN
                       CEIL((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT) / 250.0) * 300
                     WHEN SOI.WRK_CD IN ('70801') AND SOI.OPT_DC IN ('11202','11201') AND SOI.OPT_DC2 IN ('20502') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                       * ((COALESCE(SOD.HRZN_QT,1)/1000)*2*CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.WRK_CD IN ('70801') AND SOI.OPT_DC IN ('11202','11201') AND SOI.OPT_DC2 IN ('20503') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                       * ((COALESCE(SOD.VTCL_QT,1)/1000)*2*CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.WRK_CD IN ('70801') AND SOI.OPT_DC IN ('11202','11201') AND SOI.OPT_DC2 IN ('20507','20508') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                       * ((COALESCE(SOD.HRZN_QT,1)/1000)*CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.WRK_CD IN ('70801') AND SOI.OPT_DC IN ('11202','11201') AND SOI.OPT_DC2 IN ('20509','20510') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                       * ((COALESCE(SOD.VTCL_QT,1)/1000)*CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                     WHEN SOI.WRK_CD IN ('70801') AND SOI.OPT_DC IN ('11202','11201') AND SOI.OPT_DC2 IN ('20501') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                       * (((COALESCE(SOD.HRZN_QT,1)/1000)*2*CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                       + ((COALESCE(SOD.VTCL_QT,1)/1000)*2*CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END))
                     WHEN SOI.WRK_CD IN ('70811') AND SOI.OPT_DC IN ('10909','10910') THEN
                       ((COALESCE(SOD.HRZN_QT,1)/1000)*CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                       * (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                     WHEN SOI.WRK_CD IN ('70811') AND SOI.OPT_DC IN ('10913') THEN
                       ((COALESCE(SOD.HRZN_QT,1)/1000)*2*CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                       * (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT)
                     WHEN SOI.WRK_CD IN ('60201','60202','60203','60204','60206','60301','60302','60303','60304','60305','60306','70804','70201','70806','70901','70902','70903','70904','70905') THEN
                       (CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                        * CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                       * COALESCE(SOD.HRZN_QT,1)/1000 * COALESCE(SOD.VTCL_QT,1)/1000
                     WHEN SOI.UP_ORGN_CD IN ('OP903','OP904','OP905','OP906','OP907') THEN
                       ((CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                        * CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END)
                        * COALESCE(SOD.HRZN_QT,1)/1000 * COALESCE(SOD.VTCL_QT,1)/1000)
                       + CASE WHEN (COALESCE(SOD.HRZN_QT,1)/1000 * COALESCE(SOD.VTCL_QT,1)/1000) <= 0.25 THEN COALESCE(POI.MIN_VAL_AMT1,0) ELSE 0 END
                     ELSE
                       CASE WHEN COALESCE(MC.FLAG_CD,'N')='N' THEN COALESCE(POI.INSD_UM,0) ELSE COALESCE(POI.OSRC_UM,0) END
                       * CASE WHEN SOI.PAGE_QT=0 THEN 1 ELSE SOI.PAGE_QT END * SOI.ORD_QT
                   END,0) AS SAL_AMT
              FROM SD_ORDER_MST_X20329 SOM
              INNER JOIN SD_ORDER_DTL_X20329 SOD ON SOM.COMPANY_CD=SOD.COMPANY_CD AND SOM.PLANT_CD=SOD.PLANT_CD AND SOM.ORDDOC_NO=SOD.ORDDOC_NO
              INNER JOIN SD_ORDDIG_INFO_X20329 SOI ON SOD.COMPANY_CD=SOI.COMPANY_CD AND SOD.ORDDOC_NO=SOI.ORDDOC_NO AND SOD.ORDDOC_SQ=SOI.ORDDOC_SQ AND SOD.PLANT_CD=SOI.PLANT_CD
              LEFT JOIN MA_CODEDTL A ON A.SYSDEF_CD=SOI.WRK_CD AND A.COMPANY_CD='1000' AND A.MODULE_CD='SD' AND A.FIELD_CD='Z010_20329'
              LEFT JOIN MA_CODEDTL C ON C.SYSDEF_CD=SOI.CONFIG_CD AND C.COMPANY_CD='1000' AND C.MODULE_CD='SD' AND C.FIELD_CD='Z019_20329'
              LEFT JOIN MA_CODEDTL B ON B.SYSDEF_CD=SOI.OPT_DC AND B.COMPANY_CD='1000' AND B.MODULE_CD='PP' AND B.FIELD_CD='Z009_20329'
              LEFT JOIN MA_CODEDTL D ON D.SYSDEF_CD=SOI.OPT_DC2 AND D.COMPANY_CD='1000' AND D.MODULE_CD='PP' AND D.FIELD_CD='Z010_20329'
              LEFT JOIN MA_CODEDTL MC ON SOD.COMPANY_CD=MC.COMPANY_CD AND SOD.PRPL_CD=MC.SYSDEF_CD AND MC.MODULE_CD='SD' AND MC.FIELD_CD='Z021_20329'
              LEFT JOIN PP_ORDPOD_DTL_X20329 POD ON POD.COMPANY_CD=SOD.COMPANY_CD AND POD.ORDDOC_NO=SOD.ORDDOC_NO AND POD.ORDDOC_SQ=SOD.ORDDOC_SQ
              LEFT JOIN MA_CODEDTL MC2 ON MC2.COMPANY_CD='1000' AND MC2.MODULE_CD='PP' AND MC2.FIELD_CD='Z017_20329' AND MC2.SYSDEF_CD=POD.PRGR_ST
              LEFT JOIN CI_ITEM CI2 ON SOI.MTRIL_CD=CI2.ITEM_CD
              INNER JOIN MA_DEPT_MST MDM ON SOM.COMPANY_CD=MDM.COMPANY_CD AND SOM.DEPT_CD=MDM.DEPT_CD
                   AND TO_CHAR(SYSDATE,'YYYYMMDD') BETWEEN MDM.DEPT_START_DT AND MDM.DEPT_END_DT
              LEFT JOIN PP_OPTPRI_INFO_X20329 POI ON SOI.COMPANY_CD=POI.COMPANY_CD AND SOI.PLAN_PLANT_CD=POI.PLANT_CD AND SOI.WRK_CD=POI.WRK_CD AND SOI.UP_ORGN_CD=POI.UP_ORGN_CD AND SOI.CONFIG_CD=POI.CONFIG_CD AND COALESCE(SOI.OPT_DC,'X')=POI.OPT_CD1 AND COALESCE(SOI.OPT_DC2,'X')=POI.OPT_CD2 AND COALESCE(SOI.OPT_DC3,'X')=POI.OPT_CD3 AND COALESCE(SOI.OPT_DC4,'X')=POI.OPT_CD4 AND COALESCE(SOI.OPT_DC5,'X')=POI.OPT_CD5
               AND NVL(POI.USE_YN,'Y')='Y'
               AND ((POI.PARTNER_CD_USE_YN='Y' AND TRIM(POI.PARTNER_CD)=(CASE WHEN TRIM(SOM.PARTNER_CD)='00937' THEN 'P34156' ELSE TRIM(SOM.PARTNER_CD) END))
                 OR (NVL(POI.PARTNER_CD_USE_YN,'N')='N' AND NOT EXISTS (
                      SELECT 1 FROM PP_OPTPRI_INFO_X20329 P_SPEC
                       WHERE P_SPEC.COMPANY_CD=POI.COMPANY_CD AND P_SPEC.PLANT_CD=POI.PLANT_CD
                         AND P_SPEC.WRK_CD=POI.WRK_CD AND P_SPEC.UP_ORGN_CD=POI.UP_ORGN_CD
                         AND P_SPEC.CONFIG_CD=POI.CONFIG_CD
                         AND P_SPEC.OPT_CD1=POI.OPT_CD1 AND P_SPEC.OPT_CD2=POI.OPT_CD2
                         AND P_SPEC.OPT_CD3=POI.OPT_CD3 AND P_SPEC.OPT_CD4=POI.OPT_CD4 AND P_SPEC.OPT_CD5=POI.OPT_CD5
                         AND P_SPEC.PARTNER_CD_USE_YN='Y' AND TRIM(P_SPEC.PARTNER_CD)=(CASE WHEN TRIM(SOM.PARTNER_CD)='00937' THEN 'P34156' ELSE TRIM(SOM.PARTNER_CD) END)
                         AND NVL(P_SPEC.USE_YN,'Y')='Y')))
             WHERE SOM.COMPANY_CD='1000' AND SOM.PLAN_PLANT_CD='2000'
               AND TRIM(SOM.ORD_DT) >= ? AND TRIM(SOM.ORD_DT) < ?
               AND (POD.PRGR_ST IS NULL OR POD.PRGR_ST NOT IN ('700','001'))
               AND SOD.PRPL_CD IN ('G0500')
               AND NVL(SOI.ETC_DC,'N') NOT IN ('Y','P')
             ORDER BY SOM.ORD_DT, SOI.ORDDOC_NO, SOI.ORDDOC_SQ, SOI.LINE_SQ
            """;
        return jdbcTemplate.query(sql, (rs, rowNum) -> PodProductionDto.SpecRow.builder()
                .orderNo(rs.getString("ORDDOC_NO")).orderSq(intOrNull(rs, "ORDDOC_SQ")).lineSq(intOrNull(rs, "LINE_SQ"))
                .orderDate(rs.getString("ORD_DT"))
                .deptCd(rs.getString("DEPT_CD")).deptName(rs.getString("DEPT_NM"))
                .productionStatus(rs.getString("PRGR_ST_NM"))
                .itemCd(rs.getString("ITEM_CD"))
                .workCd(rs.getString("WRK_CD")).workName(rs.getString("WRK_NM"))
                .configCd(rs.getString("CONFIG_CD")).configName(rs.getString("CONFIG_NM"))
                .option1Cd(rs.getString("OPT_DC")).option1Name(rs.getString("OPT1_NM"))
                .option2Cd(rs.getString("OPT_DC2")).option2Name(rs.getString("OPT2_NM"))
                .workPlaceCd(rs.getString("PRPL_CD")).workPlaceName(rs.getString("PRPL_NM"))
                .wcFg(rs.getString("WC_FG"))
                .horizontal(decimal(rs,"HRZN_QT")).vertical(decimal(rs,"VTCL_QT"))
                .pageQty(decimal(rs,"PAGE_QT")).imposePages(rs.getString("ETC_DC3"))
                .orderQty(decimal(rs,"ORD_QT")).unitAmount(decimal(rs,"UNIT_AMT")).amount(decimal(rs,"SAL_AMT"))
                .build(), startStr, endStr);
    }

    private static Integer intOrNull(ResultSet rs, String col) throws SQLException {
        java.math.BigDecimal v = rs.getBigDecimal(col);
        return v == null ? null : v.intValue();
    }

    private PodProductionDto.Row mapRow(ResultSet rs, int rowNum) throws SQLException {
        return PodProductionDto.Row.builder()
                .workPlaceCd(rs.getString("PRPL_CD")).workPlaceName(rs.getString("PRPL_NM"))
                .orderNo(rs.getString("ORDDOC_NO")).orderSq(rs.getInt("ORDDOC_SQ"))
                .orderName(rs.getString("ORDDOC_NM")).orderDate(rs.getString("ORD_DT"))
                .salesDepartmentCd(rs.getString("SALES_DEPT_CD")).salesDepartmentName(rs.getString("SALES_DEPT_NM"))
                .salesEmployeeName(rs.getString("BIZRSPT_EMPNO_NM")).itemType(rs.getString("ITEM_FG"))
                .itemCd(rs.getString("ITEM_CD")).itemName(rs.getString("ITEM_NM")).detailItemName(rs.getString("SPCFCS_ITEM_NM"))
                .orderQty(decimal(rs,"ORD_QT")).totalPages(decimal(rs,"PAGE_QT")).imposePages(decimal(rs,"ETC_DC3"))
                .imposedTotalPages(decimal(rs,"TOTAL_PAGE_QT")).amount(decimal(rs,"SUM_AMT"))
                .size(rs.getString("SIZE_QT")).packingMethod(rs.getString("PACK_MTHD_NM"))
                .printDirection(rs.getString("PRINT_DIRECTION")).deliveryDueAt(rs.getString("DLVSH_DTS"))
                .productionEmployeeName(rs.getString("PP_ASGNR_NM")).productionStatus(rs.getString("PRGR_ST"))
                .completedAt(rs.getString("WRK_DTS")).build();
    }

    private static BigDecimal decimal(ResultSet rs, String column) throws SQLException { return rs.getBigDecimal(column); }
    private static boolean hasText(String value) { return value != null && !value.trim().isEmpty(); }
}
