CREATE TABLE teams_notification_log (
    notification_log_id BIGINT NOT NULL AUTO_INCREMENT,
    notification_type   VARCHAR(30)  NOT NULL COMMENT 'Notification type such as PRODUCTION_STATUS',
    chat_id              VARCHAR(255) NOT NULL COMMENT 'Microsoft Teams chat id',
    author_id            VARCHAR(100) NULL COMMENT 'ERP order creator id that caused the notification',
    sales_dept_cd        INT          NULL,
    sales_dept_nm        VARCHAR(100) NULL,
    order_no             VARCHAR(30)  NULL,
    order_sq             INT          NULL,
    erp_order_no         VARCHAR(30)  NULL,
    event_code           VARCHAR(30)  NULL COMMENT 'PROGRESS_ERROR, CANCELLED, etc.',
    event_name           VARCHAR(100) NULL,
    message_content      TEXT         NULL,
    delivery_status      VARCHAR(20)  NOT NULL COMMENT 'SUCCESS or FAILED',
    error_message        TEXT         NULL,
    sent_at              DATETIME     NOT NULL,
    created_at           DATETIME     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (notification_log_id),
    INDEX idx_teams_notification_sent_at (sent_at),
    INDEX idx_teams_notification_chat_sent (chat_id, sent_at),
    INDEX idx_teams_notification_author_sent (author_id, sent_at),
    INDEX idx_teams_notification_dept_sent (sales_dept_cd, sent_at),
    INDEX idx_teams_notification_event_sent (event_code, sent_at)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
