ALTER TABLE sales_dtl ADD COLUMN delivery_fee BIGINT NOT NULL DEFAULT 0;
ALTER TABLE sales_dtl ADD COLUMN design_fee BIGINT NOT NULL DEFAULT 0;
ALTER TABLE sales_dtl ADD COLUMN discount BIGINT NOT NULL DEFAULT 0;
